### ISSUE TITLE
(Feature Request) Allow a separate remapper profile for each port.

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/TitanTwo#103]
Allow remapper() to have a different profile for each port.
Example:
Output: Xbox One
USB A: Switch Pro Controller -> Swap A/B and X/Y to match output.
USB B: DS4 -> Do not swap the face buttons, but swap share and touchpad click.

Can you add a way they can both be run at once?

I have tried blocking a port (set everything in the remapper to -1 so it doesn't pass a value to the console) and switching rapidly between remapper profiles (one for each port), but this uses too much memory and crashes the T2.

Link to the relevant thread:
[https://www.consoletuner.com/forum/viewtopic.php?f=27&t=7850&p=57704#p57704](url)

**Comment by juroz** [comment]
Yeah i really needs this to use a joystick in combination with mouse and move controller. They all use different buttons layouts to work good togetter

**Comment by J2Kbr** [comment]
**PablosScripts commented**

> Please see the example code here:
> 
> https://www.consoletuner.com/forum/viewtopic.php?f=25&t=8005#p58788

**Comment by AeliusSaionji** [comment]
I would really like to see this implemented. The documentation doesn't clearly state that this can't be done so I just wasted some time troubleshooting. 

Personally, I wouldn't necessarily need this if the t2 support for Xbox Elite controller did not automap paddle buttons to 18-21; something I need to unmap in most contexts (especially for switch, where 18 is screenshot).

It's cool that the titan can independently detect the paddles as buttons, but assigning a value to them by default _will_ conflict with the controller's own onboard config.

For example, I have the right paddles mapped to LT and LB for accessibility reasons. I set this on the controller's firmware and it never needs to change. When I use the Titan to allow me to use this controller on switch, the titan adds its own mappings to the paddles- one of them being screenshot. During the course of play, I will take hundreds of screenshots by accident unless I configure the titan to _not_ do this- which of course is now preventing me from using the mapping feature for other things.

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner IV and Titan Two firmware versions 1.08 (to be released soon).

Added new GPC function `get_port()` to retrieve the port which originated the normalized input value.

Example:
```
main {
    // If BUTTON_16 is active ...
    if(get_actual(BUTTON_16)) {
        // and if the value is comming from USB-B ...
        if(get_port(BUTTON_16) == PORT_USB_B) {
            // don't forward the input to the console.
            set_val(BUTTON_16, 0.0);
        }
    } 
}
```
