### ISSUE TITLE
Bluetooth module installed but not registering

### ISSUE THREAD

**Issue by cyberjetx** [J2Kbr/TitanTwo#104]
Having recently purchased a second unit and bt for both I am having issues getting the original unit to register as having the bt unit.  BT hardware install went without and issue on both units.  format SD and configure completed both units. 

New unit bt registered and showing in GTuner. I cold only get it to work using the pair wirelessly button in GTuner. So that one is in my view good. 

The original T2 will not show as having BT at all. No HCI in GTuner. 
![capture](https://user-images.githubusercontent.com/11842304/35605530-45dce58c-0617-11e8-825a-a523d1176f00.PNG)

I have tried formatting and reconfiguring multiple times.  Also verified updates
![capture1](https://user-images.githubusercontent.com/11842304/35605575-a56b9386-0617-11e8-9204-4c73f29813ab.PNG)

**Comment by J2Kbr** [comment]
After conversation via PM on the ConsoleTuner forums it was diagnosed this problem is related with a specific device.
