### ISSUE TITLE
feature request using "led_vmset" with default brightness

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/TitanTwo#107]
would like "led_vmset" to be able to blink LEDs at default brightness/intensity, the same way we can "Pass a negative value to use the 'Default LED Intensity' configured by the user in the device settings." for "led_set"

**Comment by J2Kbr** [comment]
Hi cr33dk1ller, the implementation of `led_vmset()` already uses the default LED intensity to blink the LEDs.
