### ISSUE TITLE
Joy Cons Gyro Issue

### ISSUE THREAD

**Issue by Kalokay** [J2Kbr/TitanTwo#118]
So, the Titan Two is really great, but there’s one big issue. While it recognizes the separate accelerometers in each joycon, it treats the gyro sensors as a single unit. This makes using split joycons impossible in any game where I’d like to use motion control.

For example, in Splatoon 2, the game normally handles split joycons by tying all motion aiming to the right joycon. When using the Titan Two, I’d have to lift both joycons at the exact same time and exact same way to aim. That really doesn’t work, and I suspect it’ll be the same issue for Doom and other games.

**Comment by J2Kbr** [comment]
Option to disable input(s) from controllers using Input Translator added on firmware 0.98B-30 and Gtuner IV 1.00RC-40.
