### ISSUE TITLE
Mouse wheel event in  passthrought mode is longer than via direct usb

### ISSUE THREAD

**Issue by paname75** [J2Kbr/TitanTwo#121]
`#pragma METAINFO("base", 1, 0, "paname")

init {
    mousemapping();
    keymapping();	

}

main {
	mouse_passthru();
	key_passthru();
}
`
using this simple script you can check that  the scroll line number differ by a factor of 4 compared to directly attaching the same mouse to the pc. this make some function break in game like weapon swap getting 4 events instead of one.

you can change in windows setting to move only a single line per scroll to better exhibit the issue. try with an excel file with the row numbering

Device physical setup:
Input A = g903 mouse wireless dongle but same with wired g502 
Input B = none
Output = PC multihid
Prog = PC

**Comment by J2Kbr** [comment]
Found the issue, fixed on firmware 0.98B-36. Thanks for reporting.
