### ISSUE TITLE
PS4 Crossover Support

### ISSUE THREAD

**Issue by ghost** [J2Kbr/TitanTwo#124]
Using an Xbox Elite Controller on the PS4 with the PS4 controller plugged into input B results in the controller disconnecting every few minutes. This does not happen when the PS4 controller is used on input A. This is a minor thing, but something to avoid negative response about this feature not working.

**Comment by J2Kbr** [comment]
Firmware 0.98B-34 adds flow control checking to prevent disconnection due overflow of rumble packets.

**Comment by ghost** [comment]
This is an issue as of firmware version 0.98.1.32. I'm not sure if the version you cite is newer/older but thought this would help prevent oversight. Thank you for all the hard work man!
