### ISSUE TITLE
pmem_write seems broken in the latest update

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/TitanTwo#13]
<pre>
/*
<cfgdesc>
[foo]
byteoffset	= 0
bitsize		= 16
control		= slider
default		= 100
minimum		= 1
maximum		= 1000
step		= 10
</cfgdesc>
*/

int16 foo;

main {
	static bool run = !FALSE;

	if (run) {
		load(); // should be 100
		foo++;
		save();
		load(); // should be 101 but is 25984 (0x6580 instead of 0x0065)
	}
	run = FALSE;
}

void load()
{
	pmem_load();
	pmem_read(0, &foo);
	printf("load foo: %d", foo);
}

void save()
{
	pmem_write(0, foo);
	pmem_save();
}

</pre>

**Comment by J2Kbr** [comment]
Fixed on firmware 0.75 Beta.
