### ISSUE TITLE
after update  0.98B-39 g903 mouse doesnt work anymore via wireless dongle

### ISSUE THREAD

**Issue by paname75** [J2Kbr/TitanTwo#130]
after updating to mouse passthrough is broken with g903 wireless dongle

base passthrough script with g903 doesnt work at all in multi hid output mode
it works wired used to work perfectly wth wireless dongle.

[code=gpc2]init {
mousemapping();
keymapping();
 
}
 
main {
mouse_passthru();
key_passthru();
}
 [/code]

Device physical setup:
Input A = g903 mouse wireless dongle
Input B = none
Output = PC multihid
Prog = PC

this was working perfectly before current update.. since multi-hid introduction

hid descriptor for dongle

[USB DESCRIPTOR]
12 01 00 02 00 00 00 20 6D 04 39 C5 04 39 01 02 00 01 09 02 54 00 03 01 04 A0 31 09 04 00 00 01 03 01 01 00 09 21 11 01 00 01 22 3B 00 07 05 81 03 08 00 01 09 04 01 00 01 03 01 02 00 09 21 11 01 00 01 22 94 00 07 05 82 03 10 00 01 09 04 02 00 01 03 00 00 00 09 21 11 01 00 01 22 62 00 07 05 83 03 20 00 01 

[STRING 1 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 12 
12 03 4C 00 6F 00 67 00 69 00 74 00 65 00 63 00 68 00 

[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 1A 
1A 03 55 00 53 00 42 00 20 00 52 00 65 00 63 00 65 00 69 00 76 00 65 00 72 00 

[INTERFACE 0 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 00 00 3B 
05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01 75 01 95 08 81 02 81 03 95 05 05 08 19 01 29 05 91 02 95 01 75 03 91 01 95 06 75 08 15 00 26 A4 00 05 07 19 00 2A A4 00 81 00 C0 

[INTERFACE 1 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 01 00 94 
05 01 09 02 A1 01 85 02 09 01 A1 00 05 09 19 01 29 10 15 00 25 01 95 10 75 01 81 02 05 01 16 01 80 26 FF 7F 75 10 95 02 09 30 09 31 81 06 15 81 25 7F 75 08 95 01 09 38 81 06 05 0C 0A 38 02 95 01 81 06 C0 C0 05 0C 09 01 A1 01 85 03 75 10 95 02 15 01 26 8C 02 19 01 2A 8C 02 81 00 C0 05 01 09 80 A1 01 85 04 75 02 95 01 15 01 25 03 09 82 09 81 09 83 81 60 75 06 81 03 C0 06 BC FF 09 88 A1 01 85 08 19 01 29 FF 15 01 26 FF 00 75 08 95 01 81 00 C0 

[INTERFACE 2 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 02 00 62 
06 00 FF 09 01 A1 01 85 10 75 08 95 06 15 00 26 FF 00 09 01 81 00 09 01 91 00 C0 06 00 FF 09 02 A1 01 85 11 75 08 95 13 15 00 26 FF 00 09 02 81 00 09 02 91 00 C0 06 00 FF 09 04 A1 01 85 20 75 08 95 0E 15 00 26 FF 00 09 41 81 00 09 41 91 00 85 21 95 1F 15 00 26 FF 00 09 42 81 00 09 42 91 00 C0

**Comment by J2Kbr** [comment]
Changes reverted in revision 40
