### ISSUE TITLE
Odd PS4 controller light-bar glitch when using a script.

### ISSUE THREAD

**Issue by Fen-Ria** [J2Kbr/TitanTwo#133]
I have discovered that under certain conditions, the Titan Two can glitch and cause the PS4 controller's light-bar to the wrong color.

In the script below, when using a PS4 controller and holding down right on the directional pad, the light-bar is supposed to turn green, and the Device Moniter even says it has, but the PS4 controller's light-bar is white.

Oddly enough, if the Titan Two is set to let the script control the Titan Two's light-bar, then while the PS4 controller's light-bar is white, the Titan Two's is green.

Here is the script:
```
#pragma METAINFO("LED Test", 0, 0, "Fenria")

//Use a PS4 Controller to see the glitch.
//Hold down right on the directional pad to trigger the glitch.
//Pressing left on the directional pad shows what is suppossed to happen.
//Press down on the direcional pad in order to reset the led between tests.

int8 LC = 0;

main {
	if (event_active(BUTTON_11))	{
		LC = 0;
	}
	if (event_active(BUTTON_12))	{
		LC = 1;
	}
	fLED_Control();
	combo_run(LED_Glitch);
}

combo LED_Glitch {
	fLED_Glitch(100.0);
}

void fLED_Control() {
	if (LC == 1 && led_get(LED_3, NULL) != 100.0)	{
		led_set(LED_3, 100.0, 0);
	}
	if (LC == 0 && led_get(LED_4, NULL) != 100.0)	{
		led_set(LED_4, 100.0, 0);
		led_set(LED_3, 0.0, 0);
	}
	if (LC != 0 && led_get(LED_4, NULL) != 0.0)	{
		led_set(LED_4, 0.0, 0);
	}
}

void fLED_Glitch(fix32 v) {
	LC = 0;
	if (get_val(BUTTON_13))	{
		LC = 2;
	}
	if (LC == 2 && led_get(LED_3, NULL) != v)	{
		led_set(LED_3, v, 0);
	}
}
```

**Comment by J2Kbr** [comment]
The issue here is the script is sending two consecutive LED packets to the controller with 1ms (or less) interval, causing the controller ignore the first. Moving the function `fLED_Control();` after the combo `LED_Glitch` prevents that to happen and the script have the expected behavior:

```
#pragma METAINFO("LED Test", 0, 0, "Fenria")

//Use a PS4 Controller to see the glitch.
//Hold down right on the directional pad to trigger the glitch.
//Pressing left on the directional pad shows what is suppossed to happen.
//Press down on the direcional pad in order to reset the led between tests.

int8 LC = 0;

main {
	if (event_active(BUTTON_11))	{
		LC = 0;
	}
	if (event_active(BUTTON_12))	{
		LC = 1;
	}
	combo_run(LED_Glitch);
}

combo LED_Glitch {
	fLED_Glitch(100.0);
}

main {
    fLED_Control();
}

void fLED_Control() {
	if (LC == 1 && led_get(LED_3, NULL) != 100.0)	{
		led_set(LED_3, 100.0, 0);
	}
	if (LC == 0 && led_get(LED_4, NULL) != 100.0)	{
		led_set(LED_4, 100.0, 0);
		led_set(LED_3, 0.0, 0);
	}
	if (LC != 0 && led_get(LED_4, NULL) != 0.0)	{
		led_set(LED_4, 0.0, 0);
	}
}

void fLED_Glitch(fix32 v) {
	LC = 0;
	if (get_val(BUTTON_13))	{
		LC = 2;
	}
	if (LC == 2 && led_get(LED_3, NULL) != v)	{
		led_set(LED_3, v, 0);
	}
}
```

**Comment by Fen-Ria** [comment]
Okay then.
Thank you for the information.

May I know why it only works if it's in a seperate `main` though?

The reason I ask is because I don't understand how that makes a difference, and it also breaks the script, as in the old script, when pressing left on the directional pad, the led would change to green, but no longer does in the new script.

Would it also be possible to know why the Titan Two doesn't enforce a 2ms gap between LED packets?
