### ISSUE TITLE
Gtuner IV (Titan Two) Wish List

### ISSUE THREAD

**Issue by Tech-G33K** [J2Kbr/TitanTwo#134]
Options I would like to see back in Gtuner IV such as:

-Enable remote control of slot switch on device / G8 Alternate.
-More memory Slots on the SD Card.

This topic will help the development of Gtuner IV Titan Two.

**Please share your Wish List of what you would like to see in the future releases.**

**Comment by offbeatshotz** [comment]
hmm titan one i thought you could do this by guide+ start next slot  and guide+ select for previous

**Comment by Tech-G33K** [comment]
This issue is for **Gtuner IV (Titan Two)** only discussion, Thanks.

**Comment by NeoTechni** [comment]
> -More memory Slots on the SD Card.

Agreed, since it can display letters, A-Z would be nice too.

**Comment by J2Kbr** [comment]
Additional memory slots will be provided via this suggestion: https://github.com/J2Kbr/GtunerIV/issues/237
