### ISSUE TITLE
PS3 wrong battery level read on DS4

### ISSUE THREAD

**Issue by LyuboA31** [J2Kbr/TitanTwo#136]
When using Titan Two on my PS3 with DS4 after only few hours start disconnect the controller because of low battery when in fact the battery is almost full but the PS3 shows low batt when pair the same controller to my PS4 says battery almost full i tested it with both my Dualshock 4 controllers

**Comment by J2Kbr** [comment]
Fixed on firmware 0.98B-50. thank you for reporting.
