### ISSUE TITLE
Feature Request - PS4 Remote Play without a DS4 v2

### ISSUE THREAD

**Issue by Ilitd** [J2Kbr/TitanTwo#143]
Hello,

Do you think it is possible to allow PS4 Remote Play without a DS4 v2 ? As Titan One does, but with all features that the Titan Two offers ?

Regards.

**Comment by J2Kbr** [comment]
Feature added to firmware 0.98B-52

**Comment by Ilitd** [comment]
You are the best, J2Kbr !
