### ISSUE TITLE
[Request] When you make an Android app, support broadcast intents

### ISSUE THREAD

**Issue by NeoTechni** [J2Kbr/TitanTwo#147]
Broadcast intents allow you to send out messages to every running app on the phone which is a very handy method of inter-app communication
I would in particular, like status changes on the PS4 lightbar broadcast, cause I can make an app that takes those intents, and sends them to an RGB light I'd have next to my TV. I'm sure broadcasting printf text would come in handy.

And also receive broadcast intents to change things, so I could make a program that controls the Titan from my phone. ie: Play games using my Xperia Play if I'm feeling masochistic. Or control my PS4's bluray player from a simple remote app.

This would basically be giving any Android app API access.

**Comment by misterpyrrhuloxia** [comment]
I second this feature request. I use [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm), which is an automation app and it supports receiving and sending broadcast intents. I would love to be able to add more functionality to the Gtuner Android app through intents with Tasker. For example, I could create a widget in Tasker where, when I press one of the buttons, it sends an intent to the Gtuner app, thus changing the T2 setting (or whatever). I can basically get more functionality out of the Gtuner app with the use of intents and Tasker.

**Comment by J2Kbr** [comment]
The Titan Two App (Gtuner Air) for smartphones/tablets is finally finished, as announced here:

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=12258

However, due the use Bluetooth LE for communication between the App and the device, streaming of data is not possible (e.g. constantly transmit status of buttons, leds, ffb, etc), this is a limitation imposed by the BLE standard. For this reason, at least in this initial stage, broadcast intents will not be implemented as it will not have much usability.

As for create third-party Apps, is possible connect directly to the Titan Two device using the BLE API of iOS/Android. When I have some free time I will document the Titan Two PROG protocol.
