### ISSUE TITLE
Ps4 remote play with titan two on Mac OSX

### ISSUE THREAD

**Issue by KCSkyver** [J2Kbr/TitanTwo#150]
Same titan two setting and Hori FPS plus controller worked fine with the PS4 remote play on win10, but not with the PS4 Remote Play on macOS High Sierra ver 10.13.4.  PS4 Remote play worked fine when I plugged my DS V1 Controller to my Mac Mini.

Your kind support would be much appreciated.

Thanks in advance.

**Comment by J2Kbr** [comment]
The Titan Two implements an empirical methodology to determine the host type to which it is plugged. Unfortunately is not possible distinguish between a PS4 console and a Mac computer (as it is between PS4 and PC).

The workaround to use PS4 Remote Play on Mac with the Titan Two is use a DualShock4 V2 (the one with lightbar on touchpad) at Input-B and the Input-A can then be use with any preferable controller. The DS4V2 can be unplugged after the App recognize a controller.

Note: the Titan Two output protocol must be set to "USB PlayStation 4".
