### ISSUE TITLE
Unexpected disconnects

### ISSUE THREAD

**Issue by ghost** [J2Kbr/TitanTwo#152]
I've written about this in the past on the forums but the issue is still present. I was on an update that caused my controller to disconnect and the Titan TWO to stop using any scripts. The update came along and fixed the issue so that the Titan TWO would reconnect and start the script after re-authorizing the controller. Now, a small percentage of this issue was due to my controller at the time as I had to remove and insert the cable so many times that it ruined the connection. Now, I've upgraded to a wired controller so I wouldn't face that issue again, but the controller still disconnects every couple of minutes on average when I have a script running and every 5 minutes on average when I'm not using any scripts at all. I'm completely up to date on all firmware as of writing this.

**Comment by J2Kbr** [comment]
The next firmware release (0.98B-56) adds measurements to recover pending ATL or INT transactions to prevent device disconnections.
