### ISSUE TITLE
Bluetooth pairing DS4v2 controller -> T2 hangs sometimes

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#158]
When having the DS4v2 connected once via usb cable to the titan two, I have to do the pairing again, this is fine, I understand why this is required.
I do the pairing via button (right one)  hold down on the T2 until the segment display shows the bar going down/up and then holding down share+ps button for about 6 seconds or something like that, until the ds4v2 begins to blink.

Sometimes, 1 out of 10times, it looks like it got paired, the controller LED bar matches the led color of the T2 but no input is getting through to the PS4 pro.
Shutting of the controller by holding down the PS button for about 10+ seconds and switching it on again via the PS button it doesn't connect anymore to the t2, the controller keeps blinking until it shuts down by itself.

After powercycling the T2 the DS4v2 controller works fine by just pressing the PS button (no pairing required, this seems to work) but it looks like the T2 hangs somewhere right after the pairing sometimes.

This happened for me a few times now, a friend has the same issues.
She got her T2 two days ago and I was helping here over chat getting started with it when this happened to her , also using a ds4v2. Never seen this happening with an older ds4, but those don't require pairing that often ;-)

**Comment by Scachi** [comment]
Had this happen again today, all controllers using bluetooth.
My controller ran out of power and turned off.
I grabbed another one and pressed the ps button. The light of the controller stopped blinking and changed the color to the one of the T2 but no Input got through to the game.
Another controller wasn't getting a connection after that. I had to set my T2 into P mode by holding both buttons and out of it again to be able to connect again.
That was giving my teammates some headache keeping me alive in the middle of the combat until I was in control again ;-) 

Maybe there is some bug in freeing up the now unused bluetooth connection when a paired controller is turned off ?

**Comment by Scachi** [comment]
happened again yesterday after switching the ps4 and t2 on, waiting a bit, and pressing the PS button on my controller.
The led of the controller gets the correct LED color, but no input is passed through to the ps4.
I'll check if the Device Monitor still recognizes something the next time it happens, when I have the chance to, not being in a fight in-game.

**Comment by Scachi** [comment]
It happened again.

It did work fine first, I powered down my ps4 pro.
10 Minutes later I powered up again, pressed the PS button of my controller to connect to the T2.

The ds4 connected and the led stays connected and in the color of the T2 led.
No input is regonized by the T2, checked with GTuner IV Device Monitor.
I can't switch slots by the controller button PS+L1/R1.

Forcing my controller to power off (holding PS button a long time, maybe 10 seconds) I am not able to connect via bluetooth again.
It works fine via usb connection.

GTuner IV is reporting the bluetooth module as present/found : HCI H4 (4Mbps)

I have power off with the console enabled. Maybe this is the culprit ?

**Comment by Scachi** [comment]
A friend had this happen yesterday, too.
So it is not related to my T2 or PS4 as she has the same issue.
Sometimes the controller couldn't connect via bluetooth.
We were playing the division when her controller run out of power.
Her first try to connect an other controller via bluetooth failed, the LED of the controller changed the color to the one from the T2 but no input get through to the console.
Resetting the T2 via enter/leaving P mode with both buttons and she was able to connect again.

We had an similar issue with usb connections some time ago that you fixed with a firmware update.. might this be related to that problem and also need a similar fix ?

**Comment by J2Kbr** [comment]
Hi Scachi, I am trying reproduce this issue without success. Tried many times with two controllers (old, new). Pair, disconnect, PS button, disconnect, .... Every time worked as expected.

My Titan Two was not plugged to the console and I couldn't test the case where the controller turned off due low battery.

Next time this happens with you, please check on Device Monitor if the Bluetooth port (A or B) shows the controller still connected or _None_.

Thanks.

**Comment by Scachi** [comment]
This seems not to be related to the controller getting out of power.

It still happens to me sometimes and to both of my friend using a T2 with a ps4 pro. So it may require a connected console.

I'll take a screenshot of gtuner iv device monitor the next time it happens to me and I am not in a hurry ;-)

**Comment by Scachi** [comment]
It happened again, a few minutes ago.
I powered on my PS4, my pc was already running and connected via usb cable to the prog port, but no GTuner running.

I grabbed my controller and hit the PS button, the LED lights of the controller changed correctly but no button gets to the PS4, I can't change slots with PS+L1 / R1.

Now I started GTuner IV and took that screenshot:
Bluetooth is active and the controller connected, but no Input is registered by the T2.
I am using the latest firmware and gtuner software.

![grafik](https://user-images.githubusercontent.com/22262242/49799845-44496980-fd46-11e8-8eac-d760816ea8a3.png)

Turning of the controller with long hold of PS button and truning it back on again it is not able to connect to the titan wireless anymore.
Connecting it via usb cable is working fine.

I am only able to connect via blueooth again after powercycling/P mode the Titan Two

**Comment by J2Kbr** [comment]
I believe to have found the cause of this issue. The Titan Two was not driving the reset pin of the Bluetooth module for the time indicated in the datasheet. According the datasheet a 5ms reset is required for the module to properly reset. Starting from firmware 0.98B-77, the module have 5ms reset.
