### ISSUE TITLE
Feature Request : Wireless Controller - Low-battery Power Warning into Firmware

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#160]
Is it possible to include a battery power warning for wireless controllers into the firmware of the T2 ?
So when the battery is going to run out the led or segment display does something or uses the rumbles to indicate that it runs out of power ?
Having to code that into each script is something I don't really like, it is such a basic feature for any battery powered device to run a warning somehow when it runs out of power.

I know that the console's own notification can't be used as the device seems to be connected via usb for the console, so it would be great if the T2 itself can handle it somehow without needing to script that..
The biggest issue with this as code in scripts is that everybody will choose different notifications.

Or would that use up to much space of the firmware ?

**Comment by misterpyrrhuloxia** [comment]
I second this feature request. This would be very useful and convenient to have.

**Comment by J2Kbr** [comment]
With firmware 0.98B-72 the device's display will blink the middle segment to indicate low battery (below 20%) of controller(s).

**Comment by Scachi** [comment]
Super cool ! Thank you.
