### ISSUE TITLE
With new version (Titan Two 0.98.1.65) Xim apex 

### ISSUE THREAD

**Issue by Supermandoggo** [J2Kbr/TitanTwo#167]
I have responded to a post on the Titan two website forums and I am making a post here. The issue is the most recent update now causes xim apex to not sync I am wondering if there is a way to downgrade my titan two firmware to the previous version since there was no issue with that. Also allowing people to downgrade would I hope to make it easier and less pressure in fixing new patch bugs you would just tell people to report bug and downgrade if they have any issues. Love the product

**Comment by J2Kbr** [comment]
Fixed with 0.98B-66
