### ISSUE TITLE
passthrough at 1000hz reporting as 500hz 

### ISSUE THREAD

**Issue by paname75** [J2Kbr/TitanTwo#173]
When I check the output polling rate on this website checker it always reports as 500hz max while using T2 passhtrough and 1000hz when dirtectly connected to PC.

https://zowie.benq.com/en/support/mouse-rate-checker.html

mouse is a logitech g903.

any idea ?

**Comment by sillyasskid** [comment]
The USB Multi Interface HID Output Protocol does report at 1000hz.
However, what you are seeing is normal, not a bug.
The Titan Two will only poll mice at a maximum of 500hz.
