### ISSUE TITLE
macro_run of non existing file -> cpu usage 500%

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#176]
This (from https://www.consoletuner.com/forum/viewtopic.php?f=26&t=10827)
is the piece of code that does that.
I tried the code without the macro file on my sd card and the cpu usage got 500% and the toggle button got "stuck" on a longer hold (like >500ms).

How can I prevent that code from getting "stuck"/using all cpu  when the file does not exist on the sd-card ?

```
bool mrun=FALSE;
 
main {
    if(event_active(BUTTON_16)) {
      mrun=!mrun;
      if (!mrun) macro_stop();
    }
    if (mrun) macro_run("steep.gmk");
}
```

**Comment by J2Kbr** [comment]
Some file system operations are time demanding, such as check if a file exists. In the above code, this operation is always running if the file does not exists. You can check if the file was successfully opened with macro_time(), example:
```
bool mrun = FALSE;
 
main {
    if(event_active(BUTTON_16)) {
        mrun = !mrun;
        if(mrun) {
            macro_run("steep.gmk");
            mrun = (macro_time() >= 0);
        } else macro_stop();
    }
    if(mrun) macro_run("steep.gmk");
}
```
