### ISSUE TITLE
Input Translator - Ease of use tweak

### ISSUE THREAD

**Issue by oneswitch** [J2Kbr/TitanTwo#182]
Would be nice in GTuner IV, Input Translator, Controller Remapper if you hovered over the "Input Port Remapper Mask section" and it told you that...

USB-A = INPUT-A
USB-B = INPUT-B
USB-C = OUTPUT
USB-D = PC PROG

as it's not easy to know this otherwise.

**Comment by J2Kbr** [comment]
Port labels on mouse hover added on Gtuner IV 1.00RC-88
