### ISSUE TITLE
KMG Capture: vJoy support for accessibility purposes

### ISSUE THREAD

**Issue by oneswitch** [J2Kbr/TitanTwo#183]
KMG Capture currently gives access to keyboard, mouse and game-pads.

...Gamepads does not seem to pick up unusual controls. I would especially like for it to pick-up on "vJoy" (a virtual joystick: http://vjoystick.sourceforge.net/joomla/ (and this is the version I'm using: https://www.dropbox.com/sh/0jb45pqtpi51c9g/AABrRXsOLpNIEpD30uXe9P7fa?dl=0).

If KMG could pick-up upon vJoy and allow for keystrokes to be passed through to other software, I believe I'd be able to get the OneSwitch Pulse system working, that people like Colin McDonnell use here: 

https://switchgaming.blogspot.com/2015/05/one-switch-call-of-duty.html

Fingers crossed. :) Thanks for all the brilliant work on improving the Titan Two.

**Comment by J2Kbr** [comment]
Moved to Gtuner IV area: https://github.com/J2Kbr/GtunerIV/issues/303
