### ISSUE TITLE
Titan Two stop responding randomly on 0.75

### ISSUE THREAD

**Issue by amezibra** [J2Kbr/TitanTwo#19]
console: PS4
controller: DS4.
others : nothing else.

since the upgrade to 0.75 and running a script that is fully working on previous version ,
I have random freeze where the controller become unresponsive until unplug/replugged.
T2 keep sending last input to console until controller is unplugged.

the freeze can happen twice in 10 minute and not happen again for 2 or 3 hours..
the used script is the destiny one i put on the T2 GPC repo.

**Comment by hhezart** [comment]
It happened to me 3 times within an hour last night. In one instance my script was disabled and wasn't running.

**Comment by amezibra** [comment]
update:

0.73: issue not observed
0.75: issue observed
0.76: issue not observed

so whatever has been done in 0.75, has been fixed in 0.76.

**Comment by J2Kbr** [comment]
Thanks for update this bug report, confirming 0.76 solved the issue.
