### ISSUE TITLE
GTuner IV request: Tick box for manual slot changing (held LB/RB and tap HOME)

### ISSUE THREAD

**Issue by oneswitch** [J2Kbr/TitanTwo#190]
I'm finding some users can get muddled by the facility to change slots. On the T1 you could disable this feature. It would be great if this could be the same with the T2 via the "Device Options" tick box ara under Device Configuration.

Cheers.

Barrie

**Comment by J2Kbr** [comment]
Feature added on device FW 1.03 and Gtuner IV 1.02
