### ISSUE TITLE
PSP go support

### ISSUE THREAD

**Issue by NeoTechni** [J2Kbr/TitanTwo#192]
PSP go can take dualshock 3 controllers via bluetooth.
The problem is, you'd need to be able to change the MAC addresses of both the Titan Two, and what it's paired to manually. ie: Change the target to the PSP go, and the Titan Two itself to match the MAC of a controller already previously paired to the PSP go (as a PS3 is needed to pair a controller with it)

I'd love to use the T2 on yet another device if it's possible.

**Comment by J2Kbr** [comment]
You should be able to pair the Titan Two with PSP Go following this guide:

https://www.neogaf.com/threads/connecting-ds3-to-psp-go.425437/#post-26713750

From step 1 to 8 be sure the output protocol set on the Titan Two is "USB PlayStation 3".
For step 9, configure the output protocol to "Bluetooth PlayStation 3".
