### ISSUE TITLE
Connect Bluetooth Headsets to Titan Two and PS4

### ISSUE THREAD

**Issue by jellybean44** [J2Kbr/TitanTwo#194]
I would like to propose an enhancement whereby users who play with Bluetooth headsets can connect to the Titan Two and be able to listen and use the internal mic of their hardware with the PS4.

The feedback on USB Bluetooth dongles is that they are not reliable and most of the time do not connect / pair with the PS4.

**Comment by J2Kbr** [comment]
Thank you for your suggestion. However, what you are proposing is out of the scope of the Titan Two purposes (if understood correctly, your suggestion is make the device act as an USB dongle for Bluetooth headsets).
