### ISSUE TITLE
Bluetooth Pairing Issue With Xbox One Controller While Other Controllers Are Connected

### ISSUE THREAD

**Issue by ghost** [J2Kbr/TitanTwo#196]
Pairing an Xbox One Controller to the TITAN Two via Bluetooth does not seem to work while any other input devices are actively connected to the TITAN Two also via Bluetooth. You have to disconnect any other devices first before pairing. This only seems to be the case for Xbox One controllers, the DS4 works fine from testing.

It's a pretty obscure use case and can be easily worked around, but thought it might be worth mentioning!

**Comment by J2Kbr** [comment]
Thank you for reporting this case.

I tested and indeed the Xbox One S controllers can't pair with the Titan Two while other Bluetooth connections are active. After debugging it was verified is the controller that is not replying to the Titan Two pairing requests. On the Titan Two side it seems everything are being done correctly (other devices can successfully pair in the same situation). As this is a situation that can be easily worked around (just be sure no other Bluetooth connection is active while pairing a XB1 S controller), I will close this report. Thanks.
