### ISSUE TITLE
Latest Update Bluetooth Connection Issue PS4

### ISSUE THREAD

**Issue by Looper-2** [J2Kbr/TitanTwo#198]
Reporting an issue... Cannot use the bluetooth module with Titan on PS4. No trouble synching to controller when in GTuner but when plugging into PS4... hitting PS home button does not "hook up". Please help! Thanks as always!

**Comment by J2Kbr** [comment]
On PS4 (using a controller wired) go to Settings> Devices> Bluetooth Devices.

Then disconnect all controller. This will force repairing and will allow Bluetooth connection.
