### ISSUE TITLE
XBox1 All Controllers

### ISSUE THREAD

**Issue by MMachor** [J2Kbr/TitanTwo#2]
The XBox One Elite controllers are having an issue where when the sticks are pushed over it begins to reverse direction.  This has been reported by at least two users.  Will do further testing when my unit arrives using XBox One Elite and XBox One S controllers and will update with my findings.

Edit 1:  Have reports of this happening with a normal XBox One controller as well.  Multiple users have verified the issue.  Will further test tonight using the S controller.

Edit 2:  Have tested now with Elite and S controllers personally.  When either right or left stick goes past a certain point left it swaps direction and begins to report a right movement.  Right, up, and down appeared to be fine in personal testing.

**Comment by J2Kbr** [comment]
Fixed on Titan Two firmware 0.68 Beta
