### ISSUE TITLE
Issues with Xbox Wireless Stick - Xbox Guide button gets stuck

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#204]
Forum Post by jayjayuk: 
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=12524&p=84352#p84188

"It all works ok at the start, but after a few presses of the White Xbox Guide button on the controller in order to go to the PS4 dashboard, or holding it down a few seconds i notice that it remains 'pressed' at 100%!"

"If i don't press the guide button, i can play for hours without any issues at all."

"I tried then removing the batteries from the controller which didn't fix the issue, the only way to fix it is to power cycle the Titan Two Device."

"That picture is just straight up using the Wireless Dongle connected to a PC, i have removed the PS4 from the equation here to highlight that the PS4 is irrelevant to this issue."
![grafik](https://user-images.githubusercontent.com/22262242/57330302-e6168c00-7115-11e9-8eb1-164b70698343.png)

**Comment by J2Kbr** [comment]
FW 1.03 adds delay on the GUI ACK packet to fix the reported issue.
