### ISSUE TITLE
led_set intensity 

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/TitanTwo#205]
Code such as: 
 ```
 init {
	 led_set(LED_1, 0.0, 0); // causes Xbox LED to blink
	 led_set(LED_1, 0.001, 0); // causes Xbox LED to be off, and not blink
 }
 
 main {

 }
```

causes the Xbox LED to blink. Based on the documentation of the led_set function, the intensity parameter: 
"intensity: The LED intensity level in percentage, from 0.00 to 100.00 (%). Pass a negative value to use the “Default LED Intensity” configured by the user in the device settings."

should not cause the LED to blink. Setting the intensity parameter to 0.001, however, causes the LED to properly shut turn off.

Note: 
My Xbox controller is plugged into port B of the T2,

**Comment by J2Kbr** [comment]
Possible some other Player LED (P2, P3 or P4) has the intensity and blinking parameter set. To ensure the Xbox LED to turn off set all LEDs to 0, as the following:
```
init {
    led_set(LED_1, 0.0, 0);
    led_set(LED_2, 0.0, 0);
    led_set(LED_3, 0.0, 0);
    led_set(LED_4, 0.0, 0);
}
```

**Comment by AJSinc** [comment]
Your code causes the LED to blink too, which I believe is not intended. Setting LED's to 0.0 should cause the LED to turn OFF, not flash on and off.

I have had several users try your code too and they got a flashing LED too. Using **bluetooth** the issue _does not_ happen, however, using a **wired** connection, or an **xbox wireless adapter** connection to the T2 the issue occurs.

The code you posted causes the LED to blink **wired** and **xbox wireless adapter** (We are also using the v2/v3 Xbox One controller).

However, the code below makes the LED off with a **wired** and **xbox wireless adapter** connection.
```
init {
    led_set(LED_1, 0.001, 0);
    led_set(LED_2, 0.001, 0);
    led_set(LED_3, 0.001, 0);
    led_set(LED_4, 0.001, 0);
}
