### ISSUE TITLE
Astro C40 PS4 won't authentication

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#207]
Looks like the Astro C40 doesn't authenticate on PS4.
Multiple users reported that problem..looks like you are already arware of that:

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=12519&p=84169&hilit=astro+c40#p84169
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=12659

**Comment by J2Kbr** [comment]
FW 1.03 prevents that alternate interface settings to instantiate the same USB endpoint multiple times. This update should solve compatibility issues with Astro C40. Please reopen if not.
