### ISSUE TITLE
Feature Request : Rollback/Testversions of Firmware

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#211]
This could be useful for the T1 too.
Currently you are required to get synced with the user for a specific timeframe you will put an older version online for download & install.

For tracking down issues, looks like mostly required when trying to include support newer controllers by forum posts, it will be helpful to be able to make specific versions available by request.

To avoid misusage of rollbacks you could check the login of a user and list available Rollback versions for that user via some db/table.
If a user has trouble and you want him to test an older fw you could add his login to the table along with the fireware you want him to allow to switch to.
You could use this too for making special firmware version available to specific users for testing support for new controllers.

This way users without getting in contact with you won't be able to do random rollbacks, so it stays clean like it is currently doing by just checking for newer firmwares.
Like for a github submitted issue you could provide a special fw download file.

If the issue is resolved you could remove his entry from the table again and he will no longer be able to rollback and will be forced to update to the current version again.
Endless options to improve this:
- table entry with maximum date for the entry to be active to not be required to remove/disable the entry by hand
- table entry with maximum current release version number so this entry gets disabled when you release a newer firmware
- table entry with link to github issue, when the issue gets closed the entry get disabled too.

I know this will be a lot of work but once done it would help you a lot to resolve controller compatibility issues faster.

**Comment by J2Kbr** [comment]
After the upcoming update, I will start make use of the beta releases when changes that can potentially cause issues are implemented. The user can participate of the beta release by editing the `Gtuner.cfg` file, adding the following lines at the end:

```
[Advanced]
beta_tester=true
```

With this -I believe- the needed of firmware rollbacks will be significantly reduced, saving me from implement a complex system for rollbacks.

Thanks.
