### ISSUE TITLE
Question: is the macro working correctly in this case ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#214]
I have almost no experience with macros and have no real knowledge about pointers/ by reference usage.

Changing some functions to macros allowed me to save some script size but I had trouble using the macro in this case.
I am wondering if this one is working like it should when calling a macro from inside a function that uses the variable for toggling bits by reference or if this is a bug.

Example usage in script:
```
// main setup
uint8 T1; // byteoffet=0
uint8 T3; // byteoffset=2
//  - Toggle bit offsets
#define T1_Lock               	0
#define T1_Hairtrigger        	1
#define T1_Parcour            	2
#define T1_AntiRecoilAllOn			3
#define T1_FireModeAllOn				4
#define T1_ReloadWeaponSwitch 	5
#define T1_ReloadDCGunHolster		6
#define T1_SaveToggles					7
//
#define T3_SquareLongHoldOn			0
#define T3_ScopePanicBlockOn		1
#define T3_ArmorKitTapOn				2
#define T3_StrafeOn							3
#define T3_DZoneROn							4
#define T3_DZoneLOn							5
#define T3_ReloadDCGunHolsterS	6 //square tap
#define T3_ReloadDCGunHolsterR	7 // r3 tap

main {
BT_Toggle(&T1,T1_Parcour);
}
```

This is what it did look like when using BT_Toggle_ as a function:
```
void BT_Toggle_(uint8* byte, uint8 bit) { *byte ^= 1 << bit; } 

// toggle flags
void BT_Toggle(uint8 holdbtn, uint8 pressbtn, uint8* byte, uint8 bit, char *cwrite) {
    BT_Toggle_(byte, bit);
    pmem_write(0,T1); pmem_write(2,T3);  pmem_write(19,T4); pmem_write(1,T2);
    ICPM_Update();
}
```

For using this BT_Toggle_ macro I had to change the first line insider the "void BT_Toggle(....)" function to read "*byte" instead of "byte" to get it working with the macro.
I didn't expect to have to change that. 
```
#define BT_Toggle_(_x,_y) (_x ^= 1<<_y)

// toggle flags
void BT_Toggle(uint8 holdbtn, uint8 pressbtn, uint8* byte, uint8 bit, char *cwrite) {
    BT_Toggle_(*byte, bit); // <--- here I have to use *byte
    pmem_write(0,T1); pmem_write(2,T3);  pmem_write(19,T4); pmem_write(1,T2);
    ICPM_Update();
}
```

When you need the complete script download "The Division 2" from the Online Resource.

Thank you

**Comment by J2Kbr** [comment]
What you did is correct. Placing a * in front a point is called "dereference" and means you are accessing the value which the pointer is referencing to. More info here:

https://stackoverflow.com/questions/4955198/what-does-dereferencing-a-pointer-mean
