### ISSUE TITLE
Wiimote extension

### ISSUE THREAD

**Issue by J2Kbr** [J2Kbr/TitanTwo#215]
User is reporting bumpers and trigger are swapped with Wiimote extensions.

**Comment by J2Kbr** [comment]
Tested and bumpers/triggers on Wiimote extensions are correct.

**Comment by nelsontm** [comment]
I'm still having trouble. I uploaded a video that shows the issue: [https://photos.app.goo.gl/tjHkQ18DyqAvQdot9](url)
