### ISSUE TITLE
Add support for gyro input from Wii Remote Plus/Wii Remote + Wii Motion Plus

### ISSUE THREAD

**Issue by Fajac** [J2Kbr/TitanTwo#218]
I have a Titan Two and using its PS4 controller output and Steam's PS4 controller support I'm able to use Joy-Cons to play first/third person shooters on PC with gyro aiming and it works great. But, unlike the Wii Remote, the Joy-Cons aren't the most ergonomic controllers around and, since the Wii Remote (Plus version or with Wii Motion Plus attachment) does have gyro input, it would probably be the perfect controller for gyro aiming.

**Comment by J2Kbr** [comment]
Support for Wiimote MotionPlus (3 Axis Gyroscope) added to FW 1.08 (to be release soon).
