### ISSUE TITLE
8bitdo SN30 Pro+ descriptors

### ISSUE THREAD

**Issue by NeoTechni** [J2Kbr/TitanTwo#227]
[USB DESCRIPTOR]
12 01 00 02 00 00 00 40 C8 2D 02 60 01 00 01 02 00 01 09 02 29 00 01 01 00 C0 F0 09 04 00 00 02 03 00 00 00 09 21 11 01 00 01 22 7B 00 07 05 81 03 40 00 05 07 05 02 03 40 00 10 

[STRING 1 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 26 
26 03 38 00 42 00 69 00 74 00 64 00 6F 00 20 00 53 00 46 00 33 00 30 00 20 00 50 00 72 00 6F 00 20 00 20 00 00 00 

[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 22 
22 03 38 00 42 00 69 00 74 00 44 00 6F 00 20 00 53 00 4E 00 33 00 30 00 20 00 50 00 72 00 6F 00 2B 00 

[INTERFACE 0 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 00 00 7B 
05 01 09 05 A1 01 15 00 25 01 35 00 45 01 75 01 95 0F 05 09 19 01 29 0F 81 02 95 01 81 01 05 01 25 07 46 3B 01 75 04 95 01 65 14 09 39 81 42 65 00 95 01 81 01 26 FF 00 46 FF 00 09 30 09 31 09 32 09 35 75 08 95 04 81 02 05 02 15 00 26 FF 00 09 C4 09 C5 95 02 75 08 81 02 05 08 09 43 15 00 26 FF 00 35 00 46 FF 00 75 08 95 02 91 82 09 44 91 82 09 45 91 82 09 46 91 82 C0 

MAPPING (Physical button vs what the Titan Two reads it as in PS4 mode):
dpad and the analog sticks map correctly
L1 -> L2 (button 8)
L2 -> Touch Click (button 2+20)
L3 -> Share (button 18)
R1 -> R2 (button 5)
R2 -> Options (button 3)
R2 -> Touch P1 (button 19)
Screenshot -> nothing
Home -> nothing
Select -> L3 (button 9)
Start -> R3 (button 6)
X -> Triangle (button 14) [CORRECT]
Y -> L1 (button 7)
A -> Square (button 17)
B -> Cross (button 16) [CORRECT]
motion sensing -> nothing

**Comment by J2Kbr** [comment]
Gtuner IV 1.05 includes HID configuration file for 8BitDo SN30 Pro+. (to be released soon).
