### ISSUE TITLE
port_connect issues

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#231]
At the moment port_connect seems to reinit (close/reopen) the port even when the Output Protocol is configured to use the requested one.

A user had this issue when trying to use the attached script.
[USB-HID_RapidFire_v1.00.zip](https://github.com/J2Kbr/TitanTwo/files/3587089/USB-HID_RapidFire_v1.00.zip)

His post: 
1. https://www.consoletuner.com/forum/viewtopic.php?f=23&t=13525&p=89352#p89368
solution: https://www.consoletuner.com/forum/viewtopic.php?f=23&t=13525&p=89352#p89376

His setup: mouse&keyboard on PC -> Gtuner IV KMG Capture -> XIM Apex Hub -> XIM -> XB1
The mouse wan't working at all for him. When he removed this line from the init section he got the script working:
`port_connect(PORT_USB_C, PROTOCOL_HID);`

This seems to happen too sometimes when mouse & keyboard are connected directly to the T2 and T2 Output connect to PC. Sometimes the mouse input will do no reaction on the PC then.

Is it possible to let port_connect only apply the change when the T2 is not already set to the requested protocol ?

port_status() will report only the actively used protocol. When no Output Connection is active it will return 0 for the protocol. This makes it hard to manually check with code if USB HID is already set. Right know one have to code a combo to wait for the Output to be active to check if the procotol is set correctly..or is there another simpler script solution for this ?

Can we extend the port_connect to report the T2 configured Output Protocol in case the returned status is 0 ?
Or an extra function to read the protocol set in the T2 Device Configuration ?

Seems to be related with the issue reported at the forum by creedkiller:
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=13421

**Comment by J2Kbr** [comment]
I could not reproduce (maybe is something dependent on the USB host). However, I did some improvements on the procedures executed by port_connect() which may help in this case. The changes will be available on the next 1.05B revision.
