### ISSUE TITLE
did the mouse_set handling change with some firmware version ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#232]
I have an older usb hid script that uses this combo for rapid fire for Output Protocol "USB Multi Interface HID" that isn working anymore.
~~Not sure if this only happens because of the beta as I have both my T2 updated to beta for running other tests and can't downgrade back to stable.~~
Back again at stable firmware 1.4.3.1 it still isn't working the same anymore so this didn't changed in the beta version.

Full old script attached.
[usb_antirecoil_v1.04.zip](https://github.com/J2Kbr/TitanTwo/files/3594580/usb_antirecoil_v1.04.zip)

Also I am not sure if I have changed my setup and it isn't working anymore because of using the mouse/keyboard differently. I haven't run the usb-hid script and setup for a long time.

main portion:
```
    if (mouse_get(MBUTTON_1)) {
        if (RAPID) combo_run(cRapid); // use rapid fire if enabled only
    }
```
Here is the old combo, I could set the mouse pressed/release state `mouse_set(MBUTTON_1,0); wait(0);` once and then wait the time this state should remain `wait(RapidRelease)`:
```
combo cRapid {
	mouse_set(MBUTTON_1,1);           // fire
	wait(0); wait(RapidHold);         // time the fire button is pressed
	mouse_set(MBUTTON_1,0);           // release
	wait(0); wait(RapidWait);         // time the fire button is released
}   
```

Now I have to use it like this as the real mouse press is now recognized all the time:
```
combo cRapidFire {
  wait(RapidHold);	// time the fire button is pressed
  mouse_set(MBUTTON_1,0);  	// release
  wait(RapidWait);	// time the fire button is released
}
```

**Comment by Scachi** [comment]
The whole set_mouse stuff seems to be a bit hard to use.
When I want to set a mouse button pressed or released only I end up with unwanted ghost mouse movement in the direction of the last input just by using `mouse_set(MBUTTON_1,1);`
Doesn't make much sense to mee.

I have tried a lot of different approaches and it looks like I have got it working reliable now.
Not sure if I am missing something important on how the mouse_set USB-HID stuff is supposed to work or if there is the chance to improve this mouse_set/USB-HID behaviour to make it more userfriendly.

The current version v1.05 of the script attached.
It is working reliable with the beta firmware only 1.5.1.2.
[usb_hid_antirecoil_v1.05.zip](https://github.com/J2Kbr/TitanTwo/files/3596520/usb_hid_antirecoil_v1.05.zip)


Well it seems to work on the pc. But connecting a XIM to it seems to result in hangs every few seconds. -> Video in this post: https://www.consoletuner.com/forum/viewtopic.php?f=23&t=9889&p=89500#p89492
I don't know how much of this USB-HID output protocol mode and mouse_set / pass_thru was tested.
Or it needs some more documentation as it seems to have to be used way different than one is used to when using normal console outputs / gamepad inputs.

**Comment by J2Kbr** [comment]
What you are describing is not related with the changes made recently, not sure how your script worked as expected before.

The issue is due the combination of `mouse_passthru()` with `mouse_set()`. The first function will overwrite the output buffer with the latest data received from the connected mouse, this operation will also overwrite the value previously set by `mouse_set()` (in the combo with `wait(0)` ).

To mitigate this situation, you can check if a new data report was received from the connected mouse before call `mouse_passthru()`, example:

```
#include <mouse.gph>
 
init {
    mousemapping();
}
 
main {
    if(mouse_status(MREPORT_UPDATED)) {
        mouse_passthru();
    }
}
```

**Comment by Scachi** [comment]
Thank you very much. That explains a lot.
