### ISSUE TITLE
Question : mouse_set usage for MOUSE_X, MOUSE_Y, MOUSE_WHEEL

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#235]
I am understanding now my issues with mouse_set using the USB HID protocol resulting in unwanted movements and want to ask if this is how it is designed to work. 
Please add some note for that to the GPC language reference then if this is just how it works.

If I use set_mouse for MOUSE_X, MOUSE_Y, or MOUSE_WHEEL I have to set all three of them each time in the same main loop iteration. When calling it from a combo all have to be set through the combo.

If I do use mouse_set(MOUSE_X),someval); only and later on set MOUSE_Y I will still have the last value of MOUSE_X active. The thing that I didn't realize and was driving me nuts it that also applies to the mouse wheel.

The use case was that I wanted to use anti recoil. While using a mouse connected to the T2.
For this I do need to set Y and/or X movment without mouse_status(MREPORT_UPDATED) returning TRUE. Still holding the fire button down without any movement will correctly not trigger MREPORT_UPDATE as it is still the same state/ no Input has changed.

So, when using mouse_set MOUSE_X,MOUSEY,MOUSEWHEEL I now always set all three of them and it looks like I have no unwanted movements anymore.

**Comment by J2Kbr** [comment]
Hi Scachi, what you described is 100% correct, this is how the implementation on the Titan Two works.

The last value set for a mouse filed is kept between main() iterations, not only for the ones you listed, but also for the buttons. Unless mouse_passthru() is called, which will overwrite the value set by the script.
