### ISSUE TITLE
Input Translator upgrade (MaxAim like)

### ISSUE THREAD

**Issue by oneswitch** [J2Kbr/TitanTwo#236]
Would be fantastic to get a more user-friendly Input Translator. One day. 

A stepping stone to this might be to focus on Xbox One / PS4 type controllers. The longer term aim might be to build a drag and drop control designer interface. Something where you can drag and drop pictorial representations of what your controller (aka arcade controller panel) would look like, and what the fundamental controls would do (analogue sticks, buttons, analogue triggers, gyro, accelerometer stuff. Then save the whole layout to share with others.

Big ask, I realise, but it would be much appreciated for those new to GTuner IV, or those very fond of MaxAim. Would also stop people (including me) having to dance between the Input Translator and the "F1" GPC reference table.

Give something amazing to people, and all they do is ask for more!!

**Comment by J2Kbr** [comment]
Moved to https://github.com/J2Kbr/GtunerIV/issues/344
