### ISSUE TITLE
Titan Two Xbox One Wireless Receiver Disconnecting(Still ocurring after update 1.5.3.1)

### ISSUE THREAD

**Issue by Avoidies** [J2Kbr/TitanTwo#237]
The issue with the the Wireless receiver still disconnecting from the Xbox one controller is still occurring, I've experimented a bit more on the issue and found out that even when there are no scripts loaded on the titan two the issue still disconnects from the receiver. The wireless receiver will turn off and the titan two will stay on as well as the controller but the controller will stop functioning properly. It will continue to open up the screen where it asks to turn the console off or turn off controller or restart console. So the only function it has when the receiver turns off is holding the guide button.

**Comment by J2Kbr** [comment]
Hi, the version 1.5.3.1 relates to Gtuner IV, not to the Titan Two firmware. If your Titan Two is on version 1.04, please try the 1.05 beta release following the instructions in this page:

https://www.consoletuner.com/forum/viewtopic.php?f=2&t=13510

Thanks.
