### ISSUE TITLE
Genesis Mini controller descriptors

### ISSUE THREAD

**Issue by NeoTechni** [J2Kbr/TitanTwo#238]
[USB DESCRIPTOR]
12 01 00 02 00 00 00 40 A3 0C 25 00 06 02 00 02 00 01 09 02 29 00 01 01 00 80 32 09 04 00 00 02 03 00 00 00 09 21 11 01 00 01 22 65 00 07 05 02 03 40 00 0A 07 05 81 03 40 00 0A 

[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 1C 
1C 03 33 00 42 00 20 00 63 00 6F 00 6E 00 74 00 72 00 6F 00 6C 00 6C 00 65 00 72 00 

[INTERFACE 0 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 00 00 65 
05 01 09 04 A1 01 A1 02 75 08 95 05 15 00 26 FF 00 35 00 46 FF 00 09 30 09 30 09 30 09 30 09 31 81 02 75 04 95 01 25 07 46 3B 01 65 14 09 00 81 42 65 00 75 01 95 0A 25 01 45 01 05 09 19 01 29 0A 81 02 06 00 FF 75 01 95 0A 25 01 45 01 09 01 81 02 C0 A1 02 75 08 95 04 46 FF 00 26 FF 00 09 02 91 02 C0 C0

**Comment by J2Kbr** [comment]
After checking the descriptors it seems this controller can used with the Titan Two utilizing the Generic HID driver. If it does not works, please provide more details. thank you.
