### ISSUE TITLE
(Feature Request) Add support for Xbox One Wireless Adapter.

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/TitanTwo#24]
This could potentially be implemented the same way the bluetooth module is where the firmware is loaded off of the SD card when the hardware is connected. This would avoid needing to store all of the code in the device firmware.

**Comment by J2Kbr** [comment]
Positive. This implementation is on the plan.

**Comment by J2Kbr** [comment]
Feature added on Titan Two firmware 0.93B
