### ISSUE TITLE
Titan Two Xbox One Wireless Receiver Disconnecting

### ISSUE THREAD

**Issue by Avoidies** [J2Kbr/TitanTwo#241]
The Wireless receiver for my Xbox one controller is still disconnecting. I tried everything such as trying the beta firmware for the titan two, trying different ports for the titan two, trying it on PC, etc... The issue still occurs. To review what happens, Once I sync my Xbox controller it works fine till after a few times pressing the Xbox guide button. The controller will stay on but the receiver will turn off with the titan two staying on as well with the script loaded. I cannot do anything with the controller because after the glitch/issue occurs the guide button will stay pressed and on my screen the turn off screen will pop up. I will have to sync my Xbox controller again but even after syncing it the issue occurs.

**Comment by J2Kbr** [comment]
I found an issue with XB1 controllers updated with the latest firmware. Fix for that will be released on the Titan Two FW 1.06. Thank you,
