### ISSUE TITLE
Xbox Adaptive Controller via Bluetooth - VIEW and MENU not recognised

### ISSUE THREAD

**Issue by oneswitch** [J2Kbr/TitanTwo#253]
VIEW and MENU are a problem via bluetooth.

They are recognised (via an Xbox Adaptive Controller) if connected via USB-A or USB-B. They are not via bluetooth. The Xbox Home button and everything else does seem to be fine.

**Comment by oneswitch** [comment]
I'm testing with a prototype XAC with firmware at 4.5.1680.0. I'll try to get hold of a production run unit to see if the firmware goes higher than that, perhaps explaining the problem I'm seeing.

Anyone else having this problem would do well to update the firmware on their XACs via the Xbox One settings > accessories page, or via the Microsoft Store Xbox accessories app.

**Comment by oneswitch** [comment]
Small update:

LS = nothing
LB = VIEW
RB = MENU
RS = nothing
X = Y
Y = LB

Hopefully a firmware update from 1.6.3.0 to the T2 will address this.

**Comment by J2Kbr** [comment]
Fixed on FW 2.06 Revision 1 (to be release soon).

**Comment by oneswitch** [comment]
So close! Everything seems good, apart from the home button. On a Xbox Adaptive Controller the home-button is not working at all. As I understand, it has a different assignation to a standard Xbox One controller (although on the surface doing exactly the same thing).

**Comment by J2Kbr** [comment]
Thank you for the feedback. I have already fixed the Xbox button, the new FW update will be available soon.
