### ISSUE TITLE
Add BT Xbox 360/One as output protocol ?

### ISSUE THREAD

**Issue by Ilitd** [J2Kbr/TitanTwo#256]
Hello,

Is that possible to add Bluetooth Xbox 360 or One as an output protocol ?

I am trying to use a NS Pro Controller wirelessly (paired with BT module on Titan Two) but cannot make it work on PC using "USB X360/One" while "Bluetooth PS4" works. Is that related to the output protocol ?

Best regards,
Ilitd.

**Comment by J2Kbr** [comment]
The Bluetooth protocol of Xbox One controllers is based on standard HID. This feature will be implemented soon with the `Bluetooth Multi HID Interface` output protocol. thanks.
