### ISSUE TITLE
C# API?

### ISSUE THREAD

**Issue by bootstraponline** [J2Kbr/TitanTwo#26]
Is there a C# API for the Titan Two?

**Comment by J2Kbr** [comment]
At the moment the Titan two does not have an open API, it will be implemented soon.

**Comment by evilC** [comment]
If it is anything like the T1, a C# API will be a community effort.  
I have recently (With the help of PaulaTheKoala) implemented a [C# API for the T1](https://www.consoletuner.com/forum/viewtopic.php?f=9&t=6566) (The one linked in the docs was incomplete). I intend to do the same with the T2.
