### ISSUE TITLE
KMG Capture Mode AUTO start - forgetting ticked boxes

### ISSUE THREAD

**Issue by oneswitch** [J2Kbr/TitanTwo#263]
When I restart GTuner, having set my preference for KMG Capture to automatically start (via Preferences > KMG Capture > "Automatic enter in Capture Mode" enabled.... and KMG capture set to detect "keyboard" input previously via F4)....

when I press F4, it has forgotten that I want keyboard mode started.

It would be really convenient to not have to do this every-time for some of the users I'm supporting.

Also, a very small thing.... "Automatically start Capture Mode" would be better English than "Automatic enter in Capture Mode".

**Comment by J2Kbr** [comment]
Moved to Gtuner IV GitHub: https://github.com/J2Kbr/GtunerIV/issues/374
