### ISSUE TITLE
Allow us to change the device name or device descriptor (VID:PID)

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/TitanTwo#266]
To prevent PC-based anti-cheat from picking up on T2.

**Comment by J2Kbr** [comment]
I fully understand the concerns that motivated this request. However, I am 99.5% sure we will never see an PC based anti-cheat detect the Titan Two device via programming interface name or ID as would be ineffective. Even if this eventually happens, we implement this feature immediately. Thanks.
