### ISSUE TITLE
Feature request: Full button range for HOTAS

### ISSUE THREAD

**Issue by Pr3d8or** [J2Kbr/TitanTwo#268]
As requested in [Support for additional buttons](https://www.consoletuner.com/forum/viewtopic.php?f=25&t=11404), it would be good to have direct access to the hid reports of connected controller, so there will be possible access to all inputs.

Desired HOTAS:
- Thrustmaster Warthog
- Logitech (Saitek) X52

**Comment by phillowAT** [comment]
Hi there!
i am a senior member on an Elite Dangerous Squadron (160ppl), playing on XBOX.
Almost every day, having a better HOTAS is part of our discussion, most ppl say "If there would be a better-quality solution than the HOTAS One, i´d buy it straight away".
I guess not only our squadron is seeking for better HW support on XBOX/PS4, so i guess, especially once word is spread that there is an easy solution everyone can implement, demands for TITAN can rise quickly.
Having the ability to emulate PS/XBOX flightsticks (#178) would give us additional freedom of better mappings.
Therefore, i vote for full button support and GPC online packs:)

**Comment by makattack** [comment]
Hello, I am new to GTuner, and happen to have an XBox compatible HOTAS controller (Thrustmaster T-Flight HOTAS One) that works for XBox or PC. I have captured the HID descriptors in "XBox" mode in case it might help with these requests:
XBox Mode:
`[USB DESCRIPTOR]
12 01 00 02 FF FF FF 40 4F 04 8C B6 00 01 01 02 03 01 09 02 20 00 01 01 00 A0 32 09 04 00 00 02 FF 47 D0 00 07 05 81 03 40 00 04 07 05 01 03 40 00 04 

[STRING 1 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 1A 
1A 03 54 00 68 00 72 00 75 00 73 00 74 00 6D 00 61 00 73 00 74 00 65 00 72 00 

[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 26 
26 03 54 00 2E 00 46 00 6C 00 69 00 67 00 68 00 74 00 20 00 48 00 6F 00 74 00 61 00 73 00 20 00 4F 00 6E 00 65 00 

[STRING 3 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 03 04 09 00 22 
22 03 30 00 30 00 30 00 30 00 41 00 30 00 38 00 39 00 44 00 31 00 35 00 34 00 38 00 43 00 31 00 33 00 
`

If it might help, here are the descriptors in "PC" mode:
`
[USB DESCRIPTOR]
12 01 10 01 00 00 00 40 4F 04 8D B6 00 01 01 02 00 01 09 02 22 00 01 01 00 A0 32 09 04 00 00 01 03 00 00 00 09 21 11 01 00 01 22 74 00 07 05 81 03 40 00 05 

[STRING 1 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 1A 
1A 03 54 00 68 00 72 00 75 00 73 00 74 00 6D 00 61 00 73 00 74 00 65 00 72 00 

[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 26 
26 03 54 00 2E 00 46 00 6C 00 69 00 67 00 68 00 74 00 20 00 48 00 6F 00 74 00 61 00 73 00 20 00 4F 00 6E 00 65 00 

[INTERFACE 0 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 00 00 74 
05 01 09 04 A1 01 85 01 09 30 09 31 15 00 26 FF 03 75 10 95 02 81 02 09 32 09 35 09 33 09 34 09 36 09 37 15 00 26 FF 00 75 08 95 06 81 02 09 39 15 00 25 07 35 00 46 3B 01 65 14 75 04 95 01 81 42 65 00 05 09 19 01 29 0F 15 00 25 01 75 01 95 0F 81 02 75 05 95 01 81 01 06 00 FF 09 21 75 08 95 32 81 02 06 F0 FF 09 40 85 F2 09 47 75 08 95 3F B1 02 C0 
`

**Comment by J2Kbr** [comment]
HID configuration file for X52 PRO was created and an updated HID configuration file for regular X52. Both will be included into the next Gtuner IV release. Thanks.
