### ISSUE TITLE
Computer will not boot after setting to hibernate/sleep if titan two is plunged in.

### ISSUE THREAD

**Issue by tadashisensei** [J2Kbr/TitanTwo#269]
Not sure if this is just my issue, but my PC will not go past the motherboard screen when waking up from hibernate/sleep mode until I unplug the USB to titan two.

windows 10, asus maximus VII ranger mobo

**Comment by J2Kbr** [comment]
Hi. I also have a Maximus MOBO (VII Impact). Here works as expected, I have the Titan Two full time connected via PROG port.

Not sure what is happening in your case. I believe to be something with your setup as not other user reported similar issue.
