### ISSUE TITLE
Timing precision issue with Titan Two

### ISSUE THREAD

**Issue by Yuri-12** [J2Kbr/TitanTwo#271]
Hi! I'm having some issues with timing on a longer combo. After writing with Scachi for some days, I decided to put this here, because at least part of it seems like an issue with the Titan Two itself.

I tried various different methods to pull off a combo. The regular method inside a GPC script with wait() for the timings and set_val for the inputs gives me mixed results. It seems like there is additional time used between calls, which over time adds up and causes slight imperfections in the timing, which leads to a minor desync of the script with what's going on in the game (in this case Mario on Switch), which leads to a decreased success rate, and varied results every time I run the combo. I always start it under 100% controlled conditions in-game and the end result varies slightly, and in my case leads to seemingly random success or failure of the outcome, outside of my control.

I also tried to manually draw a macro of the exact same control setup in Gtuner. I used the exact millisecond timings from the GPC script for that, and tried to run the macro. The results were even more varied and mixed. The success rate was very small, and I was really wondering why the macro playback is so inaccurate, with the exact same millisecond numbers for the timings. I even converted it back to a GPC script in Gtuner, to find out the exact same perfect timings were still present there.

I tried a different approach as well, as suggested by Scachi, where I used the elapsed_time() function to increment a global timer in the main loop. This way, with a lot of 'if'-statements inside the main loop I got an ugly, but functional replica of the original combo. And, it runs way more precisely than both the other methods. It still doesn't do the exact same thing 100% of the time though. I guess that the elapsed_time function is not always called at the perfect moment when a millisecond passed, but sometimes the other stuff like the 'if' statements are still running, resulting in additional time passing, and over time it adds up and becomes inaccurate, leading to slightly varied results in the end again.

I'd really like to be able to run a combo at millisecond precision, without any timing imperfections - or at the very least with 8ms precision, as that's what I believe the game uses for its input, it runs at 120 FPS internally. So the problems seem to start when the 'excess time' reaches a value > 8ms. Then it leads to visible results in the game, which can add up over time and lead to problems in situations where a very precise sequence of movement is required over a longer time.

I hope my description was precise enough to get to the core of this problem, and if anything at all, to make you aware of the very inaccurate macro playback, which should not be worse than a GPC script, especially since it blocks incoming controls, and thus takes on the full Titan Two for the time it runs. If anything, it should not play worse, it should play better/more precise than the GPC script.

If I can contribute anything to help this get sorted out, I will gladly do so!

**Comment by J2Kbr** [comment]
The next Gtuner IV release (1.11) and FW update (1.11) adds a new function to help synchronize inputs, combos and macros with the game frame rate.  `output_time()` returns the number of milli-seconds that has being passed since the last output data packet was sent. 

```
main {
    if(get_val(BUTTON_2)) {
        if(output_time() == 0) {
            macro_run("Example.gmk");
        }
    }
}
```
