### ISSUE TITLE
BLE keyboard support

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#275]
I know you said that this ble support isn't high/any priority at the moment..
I just recognized it looks like I haven't added it to github at all, so here it is and I would really like to put some custom ble keyboard to use.

You mentioned some years back that the T2 will support BLE input devices in the future but updated recently that implementing it isn't as easy or simple as you thought or hoped for.

No idea if supporting BLE Keyboard as a start is easier to do than full BLE HID support ?

Doing some research for using some cheap teensy/arduino boards to build like a ble receiver module that I will plug into the T2 and use that to translate ble keyboard to usb keyboard that the T2 can already handle I stumbled across some information that there is a library available for use for ble connection hosting on esp32 boards. Maybe that is able to help you ?

Link: 
https://randomnerdtutorials.com/esp32-bluetooth-low-energy-ble-arduino-ide/

**Comment by J2Kbr** [comment]
Hi Scachi. Unfortunately BLE devices cannot be supported. The BLE interface on Titan Two is dedicated for Gtuner Air connection, configured as GATT service provider (device) and not as GATT client (host).

It would be possible to support Bluetooth keyboards that uses Bluetooth BR/EDR (Bluetooth Classic).
