### ISSUE TITLE
Hori fighting commander support

### ISSUE THREAD

**Issue by Muzzie3** [J2Kbr/TitanTwo#278]
Hi, here are the usb discriptors for the hori fighting commander

[USB DESCRIPTOR]
12 01 00 02 FF FF FF 08 0D 0F 86 00 02 01 01 02 03 01 09 02 30 00 01 01 00 80 FA 09 04 00 00 02 FF 5D 01 00 10 21 10 01 01 24 81 14 03 00 03 13 02 00 03 00 07 05 81 03 20 00 04 07 05 02 03 20 00 08 
 
[STRING 1 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 1C 
1C 03 48 00 4F 00 52 00 49 00 20 00 43 00 4F 00 2E 00 2C 00 4C 00 54 00 44 00 2E 00 
 
[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 26 
26 03 46 00 69 00 67 00 68 00 74 00 69 00 6E 00 67 00 20 00 43 00 6F 00 6D 00 6D 00 61 00 6E 00 64 00 65 00 72 00 
 
[STRING 3 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 03 04 09 00 12 
12 03 31 00 32 00 33 00 34 00 30 00 30 00 30 00 30 00 
 
[USB SNIFF]
00 00 00 01 00 00 01 00 80 06 01 00 00 00 00 40 
00 00 00 02 00 00 02 01 80 06 01 00 00 00 00 40 
12 01 00 02 FF FF FF 08 0D 0F 86 00 02 01 01 02 03 01 
00 00 00 01 00 00 01 00 00 05 00 40 00 00 00 00 
00 00 00 02 00 00 02 01 00 05 00 03 00 00 00 00 
40 
00 00 00 01 00 00 01 00 80 06 01 00 00 00 00 12 
00 00 00 02 00 00 02 01 80 06 01 00 00 00 00 12 
12 01 00 02 FF FF FF 08 0D 0F 86 00 02 01 01 02 03 01 
00 00 00 01 00 00 01 00 80 06 02 00 00 00 00 FF 
00 00 00 02 00 00 02 01 80 06 02 00 00 00 00 FF 
09 02 30 00 01 01 00 80 FA 09 04 00 00 02 FF 5D 01 00 10 21 10 01 01 24 81 14 03 00 03 13 02 00 03 00 07 05 81 03 20 00 04 07 05 02 03 20 00 08 
00 00 00 01 00 00 01 00 80 06 03 EE 00 00 00 12 
00 00 00 02 00 00 02 01 80 06 03 EE 00 00 00 12 
12 03 4D 00 53 00 46 00 54 00 31 00 30 00 30 00 90 00 
00 00 00 01 00 00 01 00 80 06 03 03 04 09 00 FF 
00 00 00 02 00 00 02 01 80 06 03 03 04 09 00 FF 
12 03 31 00 32 00 33 00 34 00 30 00 30 00 30 00 30 00 
00 00 00 01 00 00 01 00 C0 90 00 00 00 04 00 10 
00 00 00 02 00 00 02 01 C0 90 00 00 00 04 00 10 
28 00 00 00 00 01 04 00 01 00 00 00 00 00 00 00 
00 00 00 01 00 00 01 00 C0 90 00 00 00 04 00 28 
00 00 00 02 00 00 02 01 C0 90 00 00 00 04 00 28 
28 00 00 00 00 01 04 00 01 00 00 00 00 00 00 00 00 01 58 55 53 42 31 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 01 00 00 01 00 80 06 03 00 00 00 00 FF 
00 00 00 02 00 00 02 01 80 06 03 00 00 00 00 FF 
04 03 09 04 
00 00 00 01 00 00 01 00 80 06 03 02 04 09 00 FF 
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 FF 
26 03 46 00 69 00 67 00 68 00 74 00 69 00 6E 00 67 00 20 00 43 00 6F 00 6D 00 6D 00 61 00 6E 00 64 00 65 00 72 00 
00 00 00 01 00 00 01 00 80 06 06 00 00 00 00 0A 
00 00 00 02 00 00 02 02 80 06 06 00 00 00 00 0A 
00 00 00 01 00 00 01 00 C1 90 00 00 00 05 00 0A 
00 00 00 02 00 00 02 02 C1 90 00 00 00 05 00 0A 
00 00 00 01 00 00 01 00 80 06 01 00 00 00 00 12 
00 00 00 02 00 00 02 01 80 06 01 00 00 00 00 12 
12 01 00 02 FF FF FF 08 0D 0F 86 00 02 01 01 02 03 01 
00 00 00 01 00 00 01 00 80 06 02 00 00 00 00 09 
00 00 00 02 00 00 02 01 80 06 02 00 00 00 00 09 
09 02 30 00 01 01 00 80 FA 
00 00 00 01 00 00 01 00 80 06 02 00 00 00 00 30 
00 00 00 02 00 00 02 01 80 06 02 00 00 00 00 30 
09 02 30 00 01 01 00 80 FA 09 04 00 00 02 FF 5D 01 00 10 21 10 01 01 24 81 14 03 00 03 13 02 00 03 00 07 05 81 03 20 00 04 07 05 02 03 20 00 08 
00 00 00 01 00 00 01 00 80 00 00 00 00 00 00 02 
00 00 00 02 00 00 02 01 80 00 00 00 00 00 00 02 
00 00 
00 00 00 01 00 00 01 00 00 09 00 01 00 00 00 00 
00 00 00 02 00 00 02 01 00 09 00 01 00 00 00 00 
00 00 00 01 00 00 01 00 80 06 03 02 04 09 00 02 
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 02 
26 03 
00 00 00 01 00 00 01 00 80 06 03 02 04 09 00 26 
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 26 
26 03 46 00 69 00 67 00 68 00 74 00 69 00 6E 00 67 00 20 00 43 00 6F 00 6D 00 6D 00 61 00 6E 00 64 00 65 00 72 00 
00 00 00 01 00 00 01 00 C1 01 01 00 00 00 00 14 
00 00 00 02 00 00 02 01 C1 01 01 00 00 00 00 14 
00 14 FF F7 FF FF C0 FF C0 FF C0 FF C0 FF 00 00 00 00 00 00 
00 00 00 01 00 00 01 00 C1 01 00 00 00 00 00 08 
00 00 00 02 00 00 02 01 C1 01 00 00 00 00 00 08 
00 14 FF F7 FF FF C0 FF 
00 00 00 01 00 00 01 00 C0 01 00 00 00 00 00 04 
00 00 00 02 00 00 02 02 C0 01 00 00 00 00 00 04 
00 00 00 01 00 02 
01 03 02 
00 00 00 01 00 02 
02 08 03 
00 00 00 01 00 02 
01 03 02 
00 00 00 01 00 02 
01 03 06 

The titan two is showing the AU code when its connected to the ps4
thx

**Comment by J2Kbr** [comment]
Support added to firmware 1.10 (yet to be released). Thank you.
