### ISSUE TITLE
Keyboard and Mouse Disconnect after around 7.5 minutes

### ISSUE THREAD

**Issue by Sminja** [J2Kbr/TitanTwo#281]
I upgraded to the latest beta version lastnight and after about 7.5 minutes of being connected to the PS5, the controller disconnects and doesn't reconnect.

Installed Software Version: Gtuner IV 1.10.1.22
Installed Firmware Version: Titan Two 1.10.1.25

Current setup:

- Titan Two Output plugged with the above firmware into PS5
- XIM Apex plugged into Port A of the Titan Two
     - Mouse and Keyboard and PS4 Controller plugged into XIM

Prior to the Beta (I noticed it was updated this morning, so the one just before it also) everything was working fine, it would do the disconnect/reconnect for the controllers but it wasn't that bad since it did reconnect...  After the update, the controller (XIM with mouse and keyboard) would stop working and I would have to connect with the PS5 controller, unplug the Titan Two and reattach it to get it to connect again.  However it would just disconnect after around 7.5 to 8.0 minutes again.

This occurs in the PS5 menu also without being in a game.

**Comment by J2Kbr** [comment]
Hi Sminja. Thank you for your report. I believe is with you I am discussing this subject on the forums. I will close here and keep the conversation there. thanks.
