### ISSUE TITLE
Supporting wired headset via Wireless Receiver on XSX

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/TitanTwo#282]
Is it possible to support wired headset via Wireless Receiver on XSX?
USB connection is fine but I couldn't get the headset to work with the receiver on XSX and the new controller using 1.10 BETA-25.  XSX detects the headset (icon at the top) but there is no sound.

**Comment by J2Kbr** [comment]
Added support for wired headset via Wireless Receiver on XSX controller.
To be released in the next 1.10 BETA update. Thank you.
