### ISSUE TITLE
Reconnecting Xbox controller via Wireless Receiver

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/TitanTwo#283]
With XSX, Wireless Receiver, new controller and 1.10 BETA-25, you cannot turn on and reconnect the controller once it has turned itself off due to (5+ minutes) inactivity, unless you take out the battery.  Would be good if we can press the Xbox button and reconnect the controller.

**Comment by J2Kbr** [comment]
Just tested with Xbox One controller and Xbox Series controller. Couldn't reproduce the issue. Was able to reconnect both controllers by pressing the Xbox button after the automatic turn off due inactivity.
