### ISSUE TITLE
switch pro-con emulation issue. accel 1Z input is fixed to 0

### ISSUE THREAD

**Issue by koyoi** [J2Kbr/TitanTwo#285]

**Comment by koyoi** [comment]
Gtuner iV 1.10,
titan two 1.10.3.1

**Comment by J2Kbr** [comment]
Hi, I have just tested the Switch Pro controller and the `ACCEL_1_Z` is working as expected. Maybe the issue you are reporting is related to the script or other configuration. Please join to our forums so we can help you with that:

https://www.consoletuner.com/forum/
