### ISSUE TITLE
Alternate remote slot change combination

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#289]
by  cwiggy78 at the forums:
```
Hi,

This has been driving me bananas for a while. I play a lot of COD and FPS in general.

Please @J2Kbr could you place an alternate remote slot combination in the firmware :

Down Slot : LS + Xbox button
UP Slot : RS + Xbox button

It is really tricky to use the existing combination as the controller bumpers are usually tied in game to grenades and such.

Kind regards
cwiggy78
```

I would like to have that option too and it was requested a lot of times already to have an alternate slot changing option.

While it is true that we can  open a menu first before pressing that combination it add more button presses to it to just change the slot.

This alternate button combination as suggested would only invoke a "run" or a "melee" attack in most games and nothing harmful like throwing a grenade as the current combination is doing.

**Comment by cwiggy78** [comment]
Hi,

Thank you for adding this request. I believe it will be a game changer for FPS users and will definitely improve the speed in which a slot change can be made on the fly.  This just improves upon an already fantastic product.

Regards

cwiggy78

**Comment by J2Kbr** [comment]
Alternate button combination for memory slot selection using the controller added to firmware 1.11. Thank you.
