### ISSUE TITLE
Bluetooth connection features

### ISSUE THREAD

**Issue by kalirenegade** [J2Kbr/TitanTwo#290]
Hello it would be nice to connect the console tuner Titan2  to a pc via Bluetooth and be able to run scripts and preform tasked as it would be if it were to be plugged in via the prog usb port. memory management, script upload,

**Comment by J2Kbr** [comment]
Bluetooth does not have enough bandwidth for Gtuner IV PROG protocol. However, for most programing task, device basic configuration and scripts configuration there is Gtuner Air that works over Bluetooth:

https://www.consoletuner.com/software/gtuner-air/
