### ISSUE TITLE
X-52 Pro Support and T.Flight One Simulation

### ISSUE THREAD

**Issue by ModifiedSoul** [J2Kbr/TitanTwo#292]
Hi
would really love the use of my X-52 Pro in Game on Xbox
1. HID File
2. Full range of button support
3. Simulate the T.Flight HOTAS One controller on the Xbox

thanks

**Comment by J2Kbr** [comment]
HID configuration file for X52 PROo was created and an updated HID configuration file for regular X52. Both will be included into the next Gtuner IV release. Thanks.
