### ISSUE TITLE
Titan Two AU code with Bluetooth once plugged into Xbox

### ISSUE THREAD

**Issue by Scuba-Steve10** [J2Kbr/TitanTwo#293]
While the Titan Two is plugged into my iMac it recognizes the controller.  Once I disconnect it from the iMac and connect it to the Xbox it has AU code.  I am able to select scripts 1 or 2 on Titan 2 button and controller vibrates.

If I plug and second Xbox controller into the Titan Two and unplug it then AU code goes away and have full function of the Bluetooth Controller,

Is there a simple fix to not have to use two controllers every time Titan Two powers off?

Thanks in Advance

**Comment by J2Kbr** [comment]
Please note that, as explained in the following documentation page, Xbox One controllers connected over Bluetooth cannot be used as the authentication controller for Xbox One, and will require another official Xbox One controller plugged directly into the Titan Two for console authentication purposes.

https://www.consoletuner.com/wiki/index.php?id=t2:usage_guides:controllers:xboxone#wireless_bluetooth
