### ISSUE TITLE
ESWAP X PRO CONTROLLER XBOX VERSION SUPPORT

### ISSUE THREAD

**Issue by ghost251313** [J2Kbr/TitanTwo#295]
J2Kbr, could you add support for ESWAP X PRO CONTROLLER, xbox version?

Follow the link for the control: http://www.thrustmaster.com/pt_BR/products/eswap-x-pro-controller

[USB DESCRIPTOR]
12 01 00 02 FF FF FF 40 4F 04 12 D0 00 01 01 02 03 01 09 02 60 00 03 01 00 A0 FA 09 04 00 00 02 FF 47 D0 00 07 05 01 03 40 00 04 07 05 81 03 40 00 04 09 04 01 00 00 FF 47 D0 00 09 04 01 01 02 FF 47 D0 00 07 05 06 01 E4 00 01 07 05 87 01 E4 00 01 09 04 02 00 00 FF 47 D0 00 09 04 02 01 02 FF 47 D0 00 07 05 03 02 40 00 00 07 05 83 02 40 00 00

[STRING 1 DESCRIPTOR]
00 00 00 03 00 00 02 01 80 06 03 01 04 09 00 1A
1A 03 54 00 68 00 72 00 75 00 73 00 74 00 4D 00 61 00 73 00 74 00 65 00 72 00

[STRING 2 DESCRIPTOR]
00 00 00 03 00 00 02 01 80 06 03 02 04 09 00 34
34 03 65 00 53 00 77 00 61 00 70 00 20 00 50 00 52 00 4F 00 20 00 43 00 6F 00 6E 00 74 00 72 00 6F 00 6C 00 6C 00 65 00 72 00 20 00 58 00 62 00 6F 00 78 00

[STRING 3 DESCRIPTOR]
00 00 00 03 00 00 02 01 80 06 03 03 04 09 00 22
22 03 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00 30 00

**Comment by J2Kbr** [comment]
Support added to FW 1.11 (to be released soon)
