### ISSUE TITLE
support for X52 still not solved with 1.11

### ISSUE THREAD

**Issue by phillowAT** [J2Kbr/TitanTwo#296]
with the newest update, i still have issues to get my X52 recognised properly, altough i have:
reformatted and reconfigured my SD card to get all .hid´s copied (can confirm that 06A30762.hid is copied too)

Guessing this is because of the different hid´s needed to cover them, see Github issue: #294

The input capabilities still haven´t changed to utilize all 38 digital / 9 analog channels on the X52

**Comment by thievery80** [comment]
will we ever have the chance to use all 36 digital and 9 analog Inputs?

**Comment by J2Kbr** [comment]
Hi, I am releasing a new Gtuner IV today, it includes a new version of the HID configuration files for X52, enabling the directional control, mapped by default to PADDLE_3 and PADDLE_4. Thanks.
