### ISSUE TITLE
Titan 2 Freeze

### ISSUE THREAD

**Issue by amezibra** [J2Kbr/TitanTwo#3]
When running the following GPC script : "destiny 1.05" published in the GPC library,

everything looks fine and works as intended until the titan two freezes after 5 or so minutes.
unplugging controller and replugging it makes the control very sluggish and very laggy until complete freeze 10 second later..

this happens when connected to the console or during dev when doing device monitor.

at this point i don't know if it's an hardware or software related problem.

**Comment by J2Kbr** [comment]
This is related with the call of `set_led`, discussed in the Gtuner IV GitHub Issues:
https://github.com/J2Kbr/GtunerIV/issues/2
