### ISSUE TITLE
(Feature Request) Add Steam Controller Support

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/TitanTwo#30]
The title says it all. Would be the ultimate controller for people who want one controller for everything they use.

**Comment by PablosScripts** [comment]
Apparently Valve have been terrible about developer support. OBSIV the owner of XIM wanted to support it too but poor documentation and communication forced him to put this on the back burner. Shame really. That company makes too much money on steam to care I guess.

**Comment by J2Kbr** [comment]
Note: In the past days I've been working on the support for the Steam controller. For my surprise it can already be used, the Titan Two recognizes it as keyboard and mouse, which could be perfectly used to play games after with some buttons remapping and sensitivity adjustments. The Steam controller also have a proprietary interface which works more like a gamepad, I am currently reversing engineering of this proprietary protocol to extend the support to this interface as well.

**Comment by CrispyPixels** [comment]
Awesome news! Just out of curiosity, (assuming reverse engineering the gamepad interface goes smoothly) how were you planning on mapping the two touchpads on the controller? Are they going to be a dpad and joystick, or were you going to have them map into the same registers as the DS4's touchpad?

**Comment by J2Kbr** [comment]
As the Titan Two have two pairs for point inputs (`POINT_1X`, `POINT_1Y`, `POINT_2X`, `POINT_2Y`) I believe we will end using those. Of course, any mapping can be done via script or input translator, accordingly the user needs.

**Comment by CrispyPixels** [comment]
Cool, that seems like the better way in my opinion. Definitely looking forward to this!

**Comment by J2Kbr** [comment]
Full support (wired, wireless) for Steam Controller added to firmware 0.98B-5.
