### ISSUE TITLE
T2 Freezing After New Xim4 Firmware

### ISSUE THREAD

**Issue by HeIIbound** [J2Kbr/TitanTwo#34]
Started On Jan 3rd
Using on latest software and firmware..

1. What is the system you are using?
PS4 with DS4 on Port B (Xim4 with DS4 on Port A)

2. Do you have a power supply on the Titan Two?
Yes, Philmore Universal Regulated Switching Power Supply
Inputs: 100-140V AC @60Hz
Output: 3, 4.5, 6.0, 7.5, 9, 12V DC (Set to 7.5V)
Current: 0-1700mA

3. The Titan Two was also connected to PC? (Gtuner)
Yes. Its been connected to the PC the whole time while..

4. How long are the USB cable you are using?
2-3ft

5. Any of the USB has Ferrite Core?
No

6. Does this setup worked at first try? or it required many plug and unplugs?
No. After setting Device/Controller to USB, then it worked.

7. Did you noticed purple light on XIM4?
**YES!! Purple lights using xim+ds4 in port A + ds4 in port B... No disconnects though.. Able to play without issue so far..**

**Note: After this setup, I tried using a DS3 on the Xim4 as instructed in the OP, but ran into several E4 issues after 10-15 minutes of play.. Replaced DS3 with a DS4 and haven't had an error since..**

**UPDATE:: Jan 5th
After updating my xim4 firmware to 20170103, the purple lights stopped, but I get a complete freeze (no keyboard/mouse response onscreen) after 10+ minutes, twice now.. It unfreezes when I disconnect the usb-pc connection.**

**Comment by shogun6x** [comment]
1. What is the system you are using?
PS4 with DS4 on Port B (Xim4 with DS4 on Port A)

2. Do you have a power supply on the Titan Two?
Yes, soulbay variable powersupply
Inputs: 100-240V AC @60Hz
Output: 3, 4.5, 6.0, 7.5, 9, 12V DC (Set to 7.5V)
Current: max 1.2A
https://www.amazon.com/SoulBay-Universa ... rger&psc=1
3. The Titan Two was also connected to PC? (Gtuner)
no

4. How long are the USB cable you are using?
10ft

5. Any of the USB has Ferrite Core?
No

6. Does this setup worked at first try? or it required many plug and unplugs?
It works initally. you have to wait for it to recognize the xim

7. Did you noticed purple light on XIM4?
No purple lights. Xim4 goes unresponsive at first. even the xim manager connected through blue tooth drops connection to it.

Only 2 things that i can think of that might be wrong is maybe my 1.2A power supply is to weak or i should get shorter PS4 cables.

here is the xim sw i am using:
firmware - 4.00.20170104
:manager - 4.00.20160405

I also tried with only 1 controller hooked up the the xim and no controller hooked up the the T2 and have the same results.

One thing ot note is when i have the powersupply hooked up it takes longer for teh T2 to lose connection with the xim but its not a set amount increase. meaning at times it can take 10 min and others it can take a hour. without the power supply it ALWAYS fails inside of 15 min or less.

**Comment by J2Kbr** [comment]
Additional note: fix purple light on PS4.

**Comment by J2Kbr** [comment]
Thanks for the reports. I am finishing a firmware update (version 0.84B), After the release, please update your Titan Two and test using the following connection procedure:

1. Connect the power supply on the Titan Two;
2. Connect the Titan Two on the console (use a short cable);
3. Connect the controller, keyboard and mouse on XIM4;
4. Connect XIM4 on the Titan Two (use a short cable).

If the problem persists, please reopen this GitHub issue.
