### ISSUE TITLE
Large SD Cards 

### ISSUE THREAD

**Issue by ChaosInTheVoid** [J2Kbr/TitanTwo#35]
8GB SDCard won't format in the GUI, a formatted fat32 SDCard doesnt work either.  2GB SDCards work fine

**Comment by J2Kbr** [comment]
Please provide the brand/model of your 8Gb sd-card, if possible, with a link to it on amazon or any other online seller. thanks.

**Comment by J2Kbr** [comment]
I've being using an 8 Gb SD-card without problems with the latest firmware release. Please reopen this issue if you still have problem.
