### ISSUE TITLE
GTunerIV Launch

### ISSUE THREAD

**Issue by ChaosInTheVoid** [J2Kbr/TitanTwo#36]
GTUNERIV launches the menu isn't available and top bar is missing. shrinking the app by the bottom right corner and hitting the maximize button fixes it.

**Comment by J2Kbr** [comment]
Hi ChaosRocket. Thanks for reporting this issue. We have an dedicated GitHub for Gtuner IV:

https://github.com/J2Kbr/GtunerIV/issues

If you are still experiencing this problem, please open an new issue on the section above linked.

Thanks.
