### ISSUE TITLE
Cross controller problem

### ISSUE THREAD

**Issue by Mysticpurple** [J2Kbr/TitanTwo#37]
I use my XB1 controller on my 360 and sometimes as im playing ill do random 360s or itll disconnect and wont reconnect unless i completely unplug it

**Comment by J2Kbr** [comment]
I assume you are using the provided Micro-USB cable to connect the Titan Two on Xbox 360.

Please check if using an short and better quality USB cable to connect the Titan Two on the console solver the problem. If not, please reopen this issue. Thanks.
