### ISSUE TITLE
Gameplay configuration

### ISSUE THREAD

**Issue by ChaosInTheVoid** [J2Kbr/TitanTwo#38]
If you extract the download and pit the folder in program files GTIVBeta appears to work fine, but the interfactive configuration button is missing as it the online content.  When I moved it to C:\ the cog appears on the game pal to configure it.

**Comment by J2Kbr** [comment]
Please note the Gtuner IV issues are located in another GitHub:
https://github.com/J2Kbr/GtunerIV/issues

The configuration descriptor files are cache locally by Gtuner IV (it is not stored on the device), if the Gtuner's directory is changed the cached files will not be found by the software and it will not show the configuration icon. To fix that just drag-and-drop the script/gamepack to the memory slot again.
