### ISSUE TITLE
Ability to use T1 as a companion device (remote profile switcher, remote LCD screen)

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/TitanTwo#4]
Please see the following thread for more details. Priority is very low.

http://www.consoletuner.com/forum/viewtopic.php?f=23&t=4310&hilit=novel

**Comment by J2Kbr** [comment]
At this stage it seems the need of use the Titan One as companion device has not a perceptible demand. This feature would offer a limited remote functionality and still requiring an USB cable connecting the Titan One to the Titan Two, which occupy an USB input of the Titan Two that may be needed for other purposes. The implementation of the Smartphones app to remotely configure and operate the Titan Two is not far in the future, this will be a much better solution for this purpose and will not require any wiring. I am closing this request for now, we can reopen this discussion if there is demand for it (after release the smartphone app). Thanks for the suggestion.
