### ISSUE TITLE
Clear Memory Slot issue

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/TitanTwo#47]
I have a problem to clear an Input Translator from a slot.
The slot works ingame and i can clear the script but not the input translator.
I've done a Firmware recovery with no luck, how to format the Titan Two's internal memory slots?

**Comment by prototypeGtuner** [comment]
After an other Firmware recovery the slot have been deleted.

**Comment by prototypeGtuner** [comment]
I don't know where is the problem but after drag and drop an other script in the slot 1 the Input Translator appears, after had been deleted! A video is better:
https://www.mediafire.com/?gg04zogxw3rhm8g
look until the end, during the time that nothing happens i'm dragging some scripts several times and at the end they appears suddenly when they should not!

**Comment by prototypeGtuner** [comment]
After formate the SD card one more time everything works fine with normal scripts and when i put a script with "1 line art codes" it make the big mess again. And the problem with the Input Translator appears in the slot 1

#pragma METAINFO(" ̿ ̿̿'̿̿\̵͇̿̿\=(•̪●)=/̵͇̿̿/'̿̿ ̿ ̿  ", 1, 0, "function")

**Comment by J2Kbr** [comment]
This issue seems to be Gtuner IV related, move to:
https://github.com/J2Kbr/GtunerIV/issues/143
