### ISSUE TITLE
Logitech G pro Gaming keyboard not recognized

### ISSUE THREAD

**Issue by paname75** [J2Kbr/TitanTwo#49]
Pro Gaming Keyboard (VID=0x046D PID=0xC339) 

T2 doesn't get any input from this simple script, T2 sees it as HID:K and all led are green but nothing is showing when key are pressed.

```
uint8 current_key;
int key_ready;
 
init {
 
}
 
main {
    if (key_get() != current_key ) {
		key_ready = 1 ;
		current_key = key_get();
		printf("Key Code: 0x%02X", current_key);
 
	}
 
}
```

any idea?
here is a fetch descriptor output:

[USB DESCRIPTOR]
12 01 00 02 00 00 00 40 6D 04 39 C3 01 13 01 02 03 01 09 02 3B 00 02 01 04 A0 FA 09 04 00 00 01 03 01 01 00 09 21 11 01 00 01 22 41 00 07 05 81 03 08 00 01 09 04 01 00 01 03 00 00 00 09 21 11 01 00 01 22 77 00 07 05 82 03 40 00 01 

[STRING 1 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 12 
12 03 4C 00 6F 00 67 00 69 00 74 00 65 00 63 00 68 00 

[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 28 
28 03 50 00 72 00 6F 00 20 00 47 00 61 00 6D 00 69 00 6E 00 67 00 20 00 4B 00 65 00 79 00 62 00 6F 00 61 00 72 00 64 00 

[STRING 3 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 03 04 09 00 1A 
1A 03 30 00 31 00 37 00 31 00 33 00 36 00 36 00 32 00 33 00 31 00 33 00 35 00 

[INTERFACE 0 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 00 00 41 
05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01 75 01 95 08 81 02 95 01 75 08 81 01 95 03 75 01 05 08 19 01 29 03 91 02 95 05 75 01 91 01 95 06 75 08 15 00 26 FF 00 05 07 19 00 2A FF 00 81 00 C0 

[INTERFACE 1 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 01 00 77 
05 01 09 06 A1 01 05 07 19 00 29 E7 15 00 26 E7 00 75 08 95 14 85 01 81 00 C0 05 0C 09 01 A1 01 85 02 15 00 25 01 75 01 95 07 09 B5 09 B6 09 B7 09 CD 09 E9 09 EA 09 E2 81 02 95 01 81 01 C0 06 43 FF 0A 02 06 A1 01 85 11 75 08 95 13 15 00 26 FF 00 09 02 81 00 09 02 91 00 C0 06 43 FF 0A 04 06 A1 01 85 12 75 08 95 3F 15 00 26 FF 00 09 04 81 00 09 04 91 00 C0

**Comment by J2Kbr** [comment]
Was made some changes on the firmware (not yet released) to try fix this issue, not 100% sure as I don't have this keyboard to test. The new firmware will possible be out during this upcoming weekend, as an revision of 0.88B.

I am closing this issue, in case you find out it didn't resolved, please reopen. thanks.

**Comment by paname75** [comment]
tested last firmware now the keyboard is working perfectly 👍 
thanks
