### ISSUE TITLE
My T2 keeps rebooting

### ISSUE THREAD

**Issue by pablogroup** [J2Kbr/TitanTwo#5]
This is 100% reproducible when I trigger two different blocks of code in my script. It's weird because it compiles perfectly and this code is unchanged since T1 and has always worked for me. 

The first block begins on line 768 (look for the title "Walk option #3"). Basically if you double tap the shoot button (LT or L2), the Titan Two crashes and restarts. 

The second block begins on line 1012 (look for the title "Sniper Mode"). To replicate this, hold the ADS button (LT or L2), then press the X button on PS4 (or the A button on XB1). 

I use similar (if not identical) code patterns all over the place so I don't know why only these two are causing the unit to crash. 

Anyway here's the code: https://www.dropbox.com/s/tw9z6l4bvqerbph/Rainbow%20Six%20Siege%20Titan%20Two%20UI.gpc?dl=0

**Comment by pablogroup** [comment]
It occurred to me this might have something to do with the use of the combo_restart function. 

I've used this in three places in my script - two of them are the two blocks of code that are causing the T2 to crash.

**Comment by pablogroup** [comment]
Ok I'm pretty confident it is the combo_restart function causing this. I changed both instances to combo_run and it's fine now. 

Interestingly the third instance of combo_restart on line 833 doesn't cause a crash (look for the section titled "AUTO-ACTIONS").

**Comment by pablogroup** [comment]
I have another thought - the one that worked has a wait time of 7000. The ones that crashed have very low wait times. I suspect it's the rapid cycling through the short wait times that's causing it. Anyway just an idea, one possible avenue for investigation...!

**Comment by hhezart** [comment]
UPDATE: I used to get very frequent PS4 device disconnects and occasional reboots.   However for the past 3 days (12+ hours of gaming), I've disconnected the PROG (Mac/Fusion/Win10) during gameplay and not once I've experience an issue.  I've added the SD back and still everything is fine.

**Comment by J2Kbr** [comment]
Thanks for the update. I will close this bug tracker then. Please post an new comment if the problem returns.
