### ISSUE TITLE
Nintendo Switch compatibility

### ISSUE THREAD

**Issue by oneswitch** [J2Kbr/TitanTwo#55]
Would be amazing to get this featured. I see there are some third party controllers.

http://www.8bitdo.com/snes30-sfc30/

**Comment by oneswitch** [comment]
8bitdo say with their latest firmware update, their (lacking analogue) controller will work with Mario Kart 8 and Zelda. No motion control though.

**Comment by colin1993** [comment]
I would love the Titan Two to be compatible with the Nintendo Switch so that I can use Joy2Key and UCR thanks to Barrie Ellis and Special Effect. I have never been able to access any Nintendo console due to the controllers, and it is a shame because they make great games that I'd really love to play! Please help!

**Comment by oneswitch** [comment]
Looks possible. Brook have just posted a video with PS3/PS4 to Switch compatibility with their basic adapters: https://www.youtube.com/watch?v=2PC3JLs34Q4

**Comment by oneswitch** [comment]
More info here: https://www.reddit.com/r/WiiUHacks/comments/5j5t2m/xbox_one_controller_working_on_wii_u/

**Comment by netarchy** [comment]
Nintendo Switch support would be good, even better if we could additionally map the gyro to the mouse as an option instead of the right thumbstick, with possibly support for a toggle between stick/gyro. Ideal for any games that support motion controls.

**Comment by oneswitch** [comment]
Seems that you can Daisy Chain a Titan One into a Brook PS3/PS4 to Wii-U (latest version) with the latest Switch firmware update from their firm. Not sure if the Daisy-Chain effect is causing some lagging. 

Colin McDonnell proved it works on a Nintendo Wii-U. I've had a few minutes with it on a Switch today. Looks hopeful. :)

**Comment by J2Kbr** [comment]
Support for Nintendo Switch and Pro controller added to Titan Two firmware 0.95B
