### ISSUE TITLE
Input Auth Priority

### ISSUE THREAD

**Issue by paname75** [J2Kbr/TitanTwo#56]
setup:

powered via jack
input A : DS4 v2
input B : Xim4 with DS4 v1
input D : keyboard
Output PS4 Pro.

on PS4 startup xim4 connected get auth'ed first. i differentiate because one show the usb icon zhen PS is pressed.

then 5 min later auth timeout and input A DS4 input doesn't register.

i need to unplug/replug input B (xim4 ) from T2 to make DS4v2 auth first (during xim4 boot sequence) and have a stable session.

is there a way to disable inputb as auth port or doesn't allow it to supersede the input A controller?

**Comment by J2Kbr** [comment]
Input-B has priority for the authentication controller. For what you are describing, connect the DS2 Pro controller on Input-B and XIM4 on Input-A.

In addition to that, the connectivity with XIM4 is now improved, as #40 .
Please reopen if this issue still not solved.
