### ISSUE TITLE
XB1 -> T2 and Xim4 not working (Purple lights and no Audio)

### ISSUE THREAD

**Issue by Monty34** [J2Kbr/TitanTwo#63]
Environment: XB1, T2 Firmware 0.92.1, XIM4 (latest Firmware), Logitech G13 & 502, Xbox controller

Steps to replicate: 
1. XIM 4 with Mice/Keyboard and Controller (Headset plugged in Headset Adapter & Controller) 
2. XIM 4 connected to T2 either in Port A or B
3. Connect T2 into XB1

Expected outcome: 
Without any script loaded, i expect the same behaviour of XIM 4 as plugged directly to the Xbox

Actual outcome: 
XIM 4 Shows purple flashing lights
No Input via Mice and Keyboard possible
No Audo via Headset, Headset is not accepted by Headset Adapter (can´t mute it)
Tested in both Inputs A & B

**Comment by J2Kbr** [comment]
Hi Montly34, an similar issue was reported in #51 
I added your comment to that GitHub issue and included a workaround to get all working in the mean time.
Thank you for reporting.
