### ISSUE TITLE
any using "while" make's T2 crash

### ISSUE THREAD

**Issue by sky418** [J2Kbr/TitanTwo#69]
Any using "while" function makes T2 crash

**Comment by J2Kbr** [comment]
Please include an example of `while` code that crashes the Titan Two. I tested with the script below and it worked as expected (without crash).
```
main {
    int i = 20;
    while(i) {
        --i;
    }
}
```

**Comment by J2Kbr** [comment]
Accordingly the PMs we exchanged on the forums, I am considering this as solved. If you still have any doubts, please PM me.

**Comment by sky418** [comment]
Sorry for long time answer
while making script was made a mistake and Compile report - OK no errors
this one
################
int s;
int r;
init {
    s = 0;
}
main {
  if(event_active(BUTTON_10)){
     test(BUTTON_10);
     }
}
void test (uint8 active){
     s ++;
     while ( s < 10){
     r = s;
     }
     if(event_active(active)) {
     printf("R = %d",r);
     }

}
##########
And T2 crash.
Then correct to
################
int s;
int r;
init {
    s = 0;
}
main {
  if(event_active(BUTTON_10)){
     test(BUTTON_10);
     }
}
void test (uint8 active){
     while ( s < 10){
     s++;
     r = s;
     }
     if(event_active(active)) {
     printf("R = %d",r);
     }

}
