### ISSUE TITLE
Mic audio issues

### ISSUE THREAD

**Issue by J2Kbr** [J2Kbr/TitanTwo#74]
Investigate user's reports of the mic audio are presenting occasional distortions - most notable on XB1, but also on PS4.

> I have audio out of my headset but no voice, and no one else can hear me. Under the Party Chat settings it says no microphone found. I use a original XB1S controller out of port A and I am hardwired using Turtle Beach 50x headset. Also, not using XIM4 or anything. **Hey, so I got it working, but now the party is complaining of static noises randomly.**

> PS4, wired Headset directly in "new" controller. While I hear my friends perfectly, they keep reporting about occasional strong distortions in my voice... apparently it sounds robotic for a few seconds.

> Right now I've got my xim 4 connected to port a and a secondary xbox controller into port b. The chat pad is connected to the secondary controller which fixes this issue. But, from time to time people tell me that I sounded robotic for a few seconds, so I guess it' still buggy.

**Comment by hiroshimus** [comment]
Hey J2KBR,

You know what, I've been using the secondary xbox one controller connected to Port B but it would seem that my voice keeps getting distorted from time to time. People were complaining about it a lot today, I just had to turn off my mic.

There have been times when it's been working pretty well though.

As a matter of fact I'm playing right now and I'm having the same issue.

Have you had any progress with this?

=)

**Comment by J2Kbr** [comment]
Gärtner
https://www.consoletuner.com/forum/viewtopic.php?p=54446#p54446
> Hello, I would like to report here because I have exactly the same problem with cable headset. New PS4 Controller in USB-B with headset and old PS4 controller in USB-A -> voice is slightly distorted/scratchy. Only new Controller in USB-A with headset, all ok. Maybe this will help you.

**Comment by J2Kbr** [comment]
Firmware revision 0.97B-8 fixes mic audio issues by requesting isochronous data earlier than to what is specified by bInterval.
