### ISSUE TITLE
(Bug Report) PS3 Crossover Not working For Backwards Compatible PS3

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/TitanTwo#75]
On a backwards compatible PS3 the Titan 2 will not work with any controller other than the DS3 when playing a PS2 game. It recognizes the controller fine, the lights turn green, but nothing seems to work. Tested with DS4, switch pro controller, Xbox one controller, and xbox 360 controller.

Update: I was helping to update a friend's T2 and decided to test his unit in the same circumstance, his kept rebooting and ended up showing an E4 code with all lights red, when mine would just refuse to send data. Both units have the latest firmware (2017/10/04). Why would they behave differently?
Edit: I pulled the lid of both units because I noticed they were behaving differently they have different colored circuit boards inside, was there a hardware revision?

Update 2: Borrowed a friend's T1: this device behaved normally when playing PS2 games. Tested with all the above listed controllers: all working normally at this time. I noticed that when I changed the controller order on the T1, its LED would change color to indicate which player it was, but the T2 would stay blue, like it thought it was the only device connected. When I had a DS3 connected to the titan 2 the controller's LEDs would change to indicate which player it was, but the T2's would not.

Update 3: PS1 games work normally at this time.

**Comment by J2Kbr** [comment]
Support for PlayStation 2 compatibility mode on PS3 added to firmware 0.96B.
