### ISSUE TITLE
MS wireless dongle (1)

### ISSUE THREAD

**Issue by ChaosInTheVoid** [J2Kbr/TitanTwo#78]
XB1 and using black MS wireless dongle.

Buttons A and B are swapped.  Latest firmware and software.

No translation tables, T2 reads “0” on screen, output is selected as XB1

https://drive.google.com/open?id=0B-TDPJl60rmEcndqWFAtWEJxWlE

Regards - Andy

**Comment by J2Kbr** [comment]
Moved your comments to the original issue related with Wireless Receiver at #71
