### ISSUE TITLE
MS wireless dongle (2)

### ISSUE THREAD

**Issue by ChaosInTheVoid** [J2Kbr/TitanTwo#79]
On XB1 with black MS wireless dongle with elite controller 

Controller disconnects after 3 min controller xbox button flashes @3.30 controller switches off.

Turning controller back on, doesn’t reconnect.  

Dongle pairing button doesn’t work until re-insertion.

**Comment by ChaosInTheVoid** [comment]
Special note re-insertion does cause automatic re-pair when controller is switched on.

**Comment by ChaosInTheVoid** [comment]
Further note controller always switches off after 3.30 even if using.

**Comment by J2Kbr** [comment]
Moved your comments to the original issue related with Wireless Receiver at #71
