### ISSUE TITLE
McCthulu PCB Fight Stick Board Double Moves on XB1 Menu

### ISSUE THREAD

**Issue by DebuRanger** [J2Kbr/TitanTwo#84]
Hi,

So when I navigate the XB1 menu using the McCthulu fight stick, it moves 2x for each move the the joystick.  So for example, if I move down one tile, it moves down two tiles.

The T2 sees it fine and it seems to work ok in the game mode like on Killer Instinct a fighting game.

When looking into Gtuner (I still don't know how to map anything...sigh) I can go to the Device Manager and see the buttons all being pressed and joystick registers.  

If you would like a webex or something to see the output or what happens on screen, let me know.  I'd be happy to assist.

**Comment by J2Kbr** [comment]
Hi, Please give more details, as the following. 

1. On the Device Monitor, can you also see the inputs being double pressed?
2. It the McCthulu the only de vice connected to the Titan Two?
3. Did you have any script or gamepack running?

Thanks.

**Comment by J2Kbr** [comment]
In addition to the above questions, please also let me know:

4. On the Device Monitor at the center area, the USB port the controller is connected and USB C shows "Full Passthru"? or just "XB1 [IN]" and "XB1 [OUT]" respectively?

Thanks.

**Comment by PablosScripts** [comment]
I had this issue with my fight stick, the solution is here: 

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=5676

**Comment by DebuRanger** [comment]
I'm so sorry for not following up with everyone.  I got totally side tracked.
I'll check the script out.  Thank You.

**Comment by J2Kbr** [comment]
Assuming this issue as solved, if not, Please comment. Thanks.
