### ISSUE TITLE
Wireless adapter for Windows not Syncing to controller when using TitanTwo on PS4

### ISSUE THREAD

**Issue by IMulligaNI** [J2Kbr/TitanTwo#88]
Having some issues on my new TitanTwo. I'm unable to sync my wireless adapter to a Xbox one controller when the TitanTwo is connected to my PS4 Pro, When the device is connected to Gtuner.  I am able to sync the controller to the adapter and can see the emulation on both controllers, when the device is removed from computer and plugged into output to PS4. The wireless adapter doesn't sync to the controller it seems, As the white light doesn't stay active. on the Dongle

Some more info on my setup in case I missed something
- Input A - Wireless Adapter
- Input B - PS4 Controller
- All three lights show green on the TitanTwo
- Output - USB on the back of my PS4 pro
- Latest Firmware
- Micro SD formatted and configured
- No scripts active or installed on Micro SD card
- USB only mode active on PS4
- Works fine when using a wired Xbox controller on Input A

**Comment by J2Kbr** [comment]
According user's reports, issues with the Xbox Wireless Adapter seems to be solved after the firmware 0.97B-2 release. Please re-open this issue if you are still having problems. Thanks.

**Comment by IMulligaNI** [comment]
still getting this problem even after installing the latest firmware

**Comment by J2Kbr** [comment]
Closing. Issue #89 replaces this.
