### ISSUE TITLE
Add configurator menu to main UI

### ISSUE THREAD

**Issue by pablogroup** [J2Kbr/TitanTwo#9]
I think this needs to be front and center - attached is a crude mockup. 
![bsnr1bn](https://cloud.githubusercontent.com/assets/22415147/18937457/b693762a-8633-11e6-9b50-930eed19950a.png)

The configurable UI is designed for people who just consume scripts instead of building them, and by extension these are the same people that aren't going to be searching deep to see all the different options. I think it makes sense to surface this somehow.

**Comment by J2Kbr** [comment]
moved to Gtuner IV GitHub issues.
