### ISSUE TITLE
New Xbox wireless adapter

### ISSUE THREAD

**Issue by monty35** [J2Kbr/TitanTwo#92]
The new version of the wireless adapter doesn´t work with the T2. I copied the files to the SD-Card but i get only a red light instead of orange and green.

System: XB1 with new XB1 wireless adapter ontroller (nothing else connected)

Monty 34 (35 at Github)

**Comment by J2Kbr** [comment]
Support for the new Xbox Wireless Adapter added on firmware 0.98B-45.

_PS.: Gtuner IV also requires to be updated and the SD  Card reconfigured._
