### ISSUE TITLE
Touchpad Click and Share Button Question

### ISSUE THREAD

**Issue by Fen-Ria** [J2Kbr/TitanTwo#93]
I have noticed that when using a ps4 controller that to use the back, select and view buttons for the 360, ps3, and xbox one controller outputs, you click the touchpad instead of pressing the share button.

Is that intentional?

**Comment by J2Kbr** [comment]
A previous firmware update changed the button assignment of the Share and Touch-click. Now the Share is BUTTON_18 and touch-click BUTTON_2, this was done to have a more consistent button mapping across the consoles.

**Comment by Fen-Ria** [comment]
May I know why that would be considered the more consistent button mapping?

I only have a computer, Xbox 360, and PS3, so I might be missing something, but having to use the touchpad as a back/select button doesn't seem to be consistent to me.

**Comment by J2Kbr** [comment]
For example, in multi platform games the function of `VIEW`, `BACK` or `SELECT` buttons on PS4 is normally bidden to the `TOUCHPAD-CLICK`, and not to the `SHARE` button.

**Comment by Fen-Ria** [comment]
Ah, okay.
Thank you for letting me know.
