### ISSUE TITLE
Add Joy-Con support

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/TitanTwo#94]
I'm not talking about Joy-Con passthrough as I know T2 isn't designed to have dual bluetooth connections, I'm referring to simply using Joy-Cons as controllers. I would love to be able to use them on my PS4 and XB1 now that the bluetooth module has been released!

**Comment by J2Kbr** [comment]
Support for Joy-Cons (over Bluetooth) added to firmware 0.98B-8.
It is possible have up to 2 Joy-Cons connected at the same time, so both left and right joy-cos can be used simultaneous.
