### ISSUE TITLE
Titan two doesn't reconize all the buttons from Logitech G502 like Xim does

### ISSUE THREAD

**Issue by juroz** [J2Kbr/TitanTwo#99]
I cant use all the buttons form my mouse. It doesn't reconize it. Please fix it so i can put the Xim4 in the trash

**Comment by J2Kbr** [comment]
All buttons should be recognizable by the Titan Two.

Please check prototype's message on the forums:

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=7791&p=57285

Comment here if that didn't solve the issue.

Thanks
